### ISSUE TITLE
view options

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#793] opened 2016-07-15 14:44 UTC
1. load the sim.
2. go to view -> view options.
3. note bottom left of dialogue has "Walker View" and "Walker Orbit View".
4. ensure that the two walker view options are not selected. mine default to not selected when i delete the c172p.xml file from the aircraft-data directory...
5. hit SHIFT-V and you should see the copilot's view.
6. hit V and you should switch to the pilot's view but you are in some weird view instead.
7. hit V again to go to the pilot's view.
8. if you left the "View Options" dialogue open, it will not have changed. now close the dialogue and re-open it. what happened to the walker view options???

**Comment by gilbertohasnofb** [comment] 2016-07-15 16:48
> 8. if you left the "View Options" dialogue open, it will not have changed. now close the dialogue and re-open it. what happened to the walker view options???

To me, nothing. I can't reproduce it. Following the steps above I see nothing wrong with the dialog, even after closing and opening it again. Would you mind posting a screen shot? 

Also, if there is a problem with the View Options dialog, it probably will have to be tackled by the devs, unless we are doing something wrong which is causing the issue.

**Comment by wkitty42** [comment] 2016-07-15 19:49
do you not see the weird screen? i think it is a walker view from being stuffed into a cabinet...

anyway, here's the pics in order of the way i described previously...

this is numbers 3 and 4 of the list...
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/4641713/16886561/1271b03c-4aa3-11e6-891b-7364730864bc.png)

this is number 5...
![fgfs-screen-002](https://cloud.githubusercontent.com/assets/4641713/16886563/127b6636-4aa3-11e6-87da-88e702b4bc87.png)

this is number 6...
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/4641713/16886562/127b4854-4aa3-11e6-85cf-88431106d959.png)

this is number 7...
![fgfs-screen-004](https://cloud.githubusercontent.com/assets/4641713/16886564/127c30e8-4aa3-11e6-8de8-b9fc7f35381c.png)

this is number 8... where'd the view options go and that single untitled box come from??
![fgfs-screen-005](https://cloud.githubusercontent.com/assets/4641713/16886565/128560dc-4aa3-11e6-9139-95cc19db6bc2.png)

**Comment by gilbertohasnofb** [comment] 2016-07-15 19:54
Hmm, I really can't reproduce this. Actually, step 6. doesn't happen to me, when I press V while on the copilot's view I come to back normally the pilot's view without any weird visuals.

**Comment by wkitty42** [comment] 2016-07-15 21:08
On 07/15/2016 03:54 PM, Gilberto Agostinho wrote:
> Hmm, I really can't reproduce this. Actually, step 6. doesn't happen to me,
> when I press V while on the copilot's view I come to back normally the
> pilot's view without any weird visuals.

interesting... i've been seeing it for a week or so... maybe longer but not very 
long...

just to be sure, too, i'm on master and have the latest c172p code... also i'm 
on 2016.3.0 with the latest code there...

maybe someone else can reproduce it?

**Comment by wlbragg** [comment] 2016-07-16 04:17
I can't reproduce this behavior either, it all appears to work correctly for me.

**Comment by wkitty42** [comment] 2016-07-16 13:37
here's what i've done...

1. i moved my local c172p to a holding directory
2. i deleted my fork of c172p-detailed in my github area
3. forked fresh from juanvvc:c172p-detailed/master to my github area
4. cloned from my (now new) wkitty42:c172p-detailed/master to my local repo
5. out of curiosity i ran "diff -r ./ the/holding/dir/" to compare the two, my possibly corrupt one with the newly forked one... the only differences were in the .git directory and then only that my old one has more entries... all the other files, those actually used for the craft, came out identical...
6. i've loaded the sim and tested as above and i still get this weirdness with that odd screen and the loss of the two walker options in the view options...

maybe this is a 2016.3.0 bug? i'll post about it to the dev-list and see what happens... can we keep this open for a while until we determine where the problem is?

**Comment by gilbertohasnofb** [comment] 2016-07-16 13:43
> maybe this is a 2016.3.0 bug? 

Could very well be. I am using 2016.2.1, as I got tired of all bugs of the unstable releases (and now the release cycle is only 3 months anyway). 

Whatever it may be, it seems to me that this bug not to be related to our craft, so I would suggest closing this. Everyone agrees?

**Comment by wkitty42** [comment] 2016-07-16 14:14
well, being as i just asked to keep it open, i guess i'm not in favor of closing it yet :stuck_out_tongue_winking_eye:  :laughing:

**Comment by gilbertohasnofb** [comment] 2016-07-16 14:18
@wkitty42 sorry, I totally oversaw the last phrase of your last post (too much multitasking at the moment), else I wouldn't have proposed it! Sure, let's see what answer you get from the dev list, just please let us know here about any findings.

**Comment by wkitty42** [comment] 2016-07-16 19:23
@gilbertohasnofb np :+1:

**Comment by wkitty42** [comment] 2016-07-24 03:55
i haven't seen anything more related to this but i have seen the exact same thing in another craft (from the FGUK hanger)... no clue yet but now that more than one craft exhibits it, it should be easier to track down...

**Comment by gilbertohasnofb** [comment] 2016-07-24 10:32
@wkitty42 and these are the only two aircraft you see this problem? Or are by any chance all aircraft which have the walker option causing the issue? Because if so, then likely it's not an aircraft specific problem. Also, could this be caused by some conflict with whatever else you have installed (I don't know, maybe Bombable or FGCamera or whatever like this?)?

**Comment by onox** [comment] 2016-07-24 16:18
I could not reproduce the problem in the screenshots.

**Comment by wkitty42** [comment] 2016-07-24 21:35
@gilbertohasnofb you may be on to something there... the other craft i saw it with is the FGUK C-17... is there a list somewhere of craft with walkers? i thought we were using our own separate walkers with some fixes or enhancements??

**Comment by gilbertohasnofb** [comment] 2016-07-24 21:37
I don't know about such a list unfortunately. As for "our" walker, it's actually FGDATA's walker :smile: None of those enhancements we once discussed were implemented, and anyway the plan would be to improve them directly on FGDATA.

**Comment by wkitty42** [comment] 2016-07-25 17:13
On 07/24/2016 05:37 PM, Gilberto Agostinho wrote:
> I don't know about such a list unfortunately. As for "our" walker, it's actually
> FGDATA's walker 😄 None of those enhancements we once discussed were
> implemented, and anyway the plan would be to improve them directly on FGDATA.

ahhh... ok... i wasn't sure and haven't gone digging to see if it was still the 
one in FGData or not... thanks for the info...

since the walker(s) exist in FGData and this problem exists in more than one 
craft, i guess we can close this issue now... i'm responding via email so i 
can't [comment and close] it... i can do so later if no one else has by the time 
i circle around to the github site...

**Comment by gilbertohasnofb** [comment] 2016-07-25 17:25
No problems, I am closing it now myself :smile:

**Closed by gilbertohasnofb** 2016-07-25 17:25 UTC
