### ISSUE TITLE
DME changed? On/Off toggle switch texture missing on all liveries...

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#253] opened 2015-06-06 20:50 UTC
I don't know how I've missed this before but I've just noticed that the DME seems to have changed and the toggle switch texture is missing... see the pic...
![fgfs-screen-048](https://cloud.githubusercontent.com/assets/4641713/8021385/222012e2-0c6c-11e5-9345-3dafbf19aeab.png)

**Comment by wkitty42** [comment] 2015-06-14 18:18
i was just checking on this to see what the status is/was... i also checked the original c172p and there is a switch... i don't know how or when we lost it, though... maybe when the panel was moved around?? here's a shot from the original c172p for comparison...

![fgfs-screen-053](https://cloud.githubusercontent.com/assets/4641713/8149823/05b45dae-12a0-11e5-8d70-d46428103ca1.png)

**Comment by onox** [comment] 2015-06-14 18:28
Sorry, but I see 1 dial, 1 on/off switch, 1 button :smile: Do you mean the texture of the on/off switch?

**Comment by gilbertohasnofb** [comment] 2015-06-14 18:30
@onox Yes, compare his two images above: the ON-DME-OFF switch looks different between the two pictures. It could be it has the same problem as the #250 but I am not sure.

**Comment by onox** [comment] 2015-06-14 18:40
Yeah, @wkitty42's description didn't mention that it was about a texture and I overlooked the title :sweat_smile:

**Comment by gilbertohasnofb** [comment] 2015-06-14 18:44
I just checked and it is about textures indeed. I can see the 3D object but it looks completely uniformly grey at some angles, and just fine at others.

**Comment by gilbertohasnofb** [comment] 2015-06-14 18:45
So I will create another 2x2 texture with light grey solid colour and we apply it to this switch.

**Comment by onox** [comment] 2015-06-14 18:46
`dme.ac` and `dme.rgb` are the same as in the old c172p.

**Comment by gilbertohasnofb** [comment] 2015-06-14 18:58
But `dme.rgb` does not contain texture for the switch, but only for the panel part of the DME.

**Comment by onox** [comment] 2015-06-14 19:10
I grepped through `dme.ac` and only found `texture "dme.rgb"`, but again I don't know much about UV and texture stuff.

**Comment by gilbertohasnofb** [comment] 2015-06-14 19:11
No problems. So it means that this texture is being used by the DME panel, but not necessary by the switch, which I believe is untextured. In that case, similarly to #250, we need to add texture to it.

**Comment by gilbertohasnofb** [comment] 2015-06-14 19:15
Okay, so we now have a texture named light-gray-texture.png located on Models. Someone with Blender knowledge just have to apply it to the DME toggle now.

**Comment by wkitty42** [comment] 2015-06-14 22:06
this looks to be fixed as of commit 7b5004ff32e8983a365cd8624b5ccd9248969ee1 ... i see a nice switch in place and it appears to work :)

**Comment by gilbertohasnofb** [comment] 2015-06-14 22:09
Are you sure? That commit has nothing to do with that switch.

**Comment by wkitty42** [comment] 2015-06-15 00:31
@gilbertohasnofb that commit may not but one of the other 8 or 10 before it appears to... i only know what the last one was that i pulled... sorry...

**Comment by onox** [comment] 2015-06-15 04:08
@wkitty42 When was the last time when you pulled (when the texture was still missing)?

**Comment by onox** [comment] 2015-06-15 04:13
I tried to `git reset --hard` all the way back to 9f0f1e7 and I can never reproduce the bug.

**Comment by onox** [comment] 2015-06-15 04:15
So `Models/light-gray-square.png` can be deleted again?

**Comment by wkitty42** [comment] 2015-06-15 09:47
these are the commits that came in when i did that last pull...

commit 7b5004ff32e8983a365cd8624b5ccd9248969ee1
commit 714169cb7dd2b6d0e367c6c93a5f7f7ddfbd6da7 (this one fixed the switch texture)
commit e6de5017956e6bdf9c56bf4c7d845230615c5ac0
commit 399db1b8d1d3d21cbf191ddfc8b85e259132e88b
commit 80d5f96070550588b88b15ce66e970b03b8861ac
commit 9dc86bc2f162eccaaa335a9914ddb7791af6de4e
commit 7a7ad478e741327813d4ad65c2b35c0994859133
commit fb7a9d847433b7a49a758d7c4475a0f2fc888395
commit 057369498a8775134b51b429464e346be749c04d
commit 26e7853f0d5957bc15967462c3762197d10313ac

i already had the next one that fixed the CTRL-C transponder label showing all the time...

to answer the question of "when do i pull?" any time i see that there's a new update... several times a day when you guys get busy ;)  i just look at my fork here on github and it tells me i'm X commits behind... when i see that i do a "fetch upstream", "merge upstream/master" and "push origin" where upstream is this repo and origin is my fork...

**Comment by wkitty42** [comment] 2015-06-15 09:51
i don't think i'd revert the commit since it did fix the problem here... having it won't hurt anything...

i wish i could find the commit where the switch texture went missing... i think it happened when the old KT70 or whatever that legacy instrument was was removed... that's when i noticed the DME's panel shape changed, too... look at the two pics above and you can see how the radio stack is different between them... in the original c172p, the AP is above the DME but in this craft, the AP is below the DME and the DME's fascia has changed from the black panel it used to be...

**Comment by onox** [comment] 2015-06-15 11:16
@wkitty42 But that commit cannot fix the issue. It's just a new file, it's not being used. And when I got back to a commit before 714169c, then I still don't have the issue, which I should if that particular would have fixed this bug.

**Comment by wkitty42** [comment] 2015-06-15 11:33
well i don't know then... something screwy seems to be going on over here that i don't understand... the craft i'm flying now doesn't have the switch texture but the one i flew yesterday did... i'm starting to wonder if some thing is going on with resources or such in the sim... like the control panel swapping issue that was recently filed... i'm gonna reopen this and so we can get it fixed properly... sorry for the noise :disappointed:

**Comment by wkitty42** [comment] 2015-06-15 11:35
> then I still don't have the issue, which I should if that particular commit would have fixed this bug.

@onox are you saying that you have a switch texture on your console? yours doesn't look like my first snapshot above???

**Comment by onox** [comment] 2015-06-15 16:26
It has a texture, it looks like the second screenshot.

**Comment by gilbertohasnofb** [comment] 2015-06-15 16:28
> It has a texture, it looks like the second screenshot.

Onox, none of the screenshots above has any texture to them, this object has a simple solid colour applied to it. What you probably mean is that you can see the 3D details to the object, the shadows, etc., but to speak about texture is not correct I think.

**Comment by onox** [comment] 2015-06-15 16:30
Yeah, that's what I meant, I can see the shape.

**Comment by onox** [comment] 2015-07-10 05:35
I cannot reproduce this issue. Closing this issue.

**Closed by onox** 2015-07-10 05:35 UTC
Labels: 3D model, bug

**Comment by wkitty42** [comment] 2015-07-10 11:29
i thought we decided that this was just a plain grey switch and that there was no chrome or black texture on it?
