### ISSUE TITLE
pgup/pgdn throttle controls

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#347] opened 2015-06-26 23:00 UTC
The new dual engine stuff is in and now the throttle control keys are too coarse... I've checked both 160hp and 180hp engines and they are the same... I used to go full power for takeoff and then once airborne hit pgdn 10 times to reduce power but now that's all different...

**Comment by onox** [comment] 2015-06-29 00:29
I have changed throttle control to be more like how mixture is. Is mixture coarse too? Because it should be and always has been.

The reason why I made throttle coarser is so that I can more easily and faster go to throttle idle or full power when landing/going around or during stall spin recovery.

@gilbertohasnofb @wlbragg @dany93 What do you think of having coarse + fine throttle/mixture control? Perhaps using the Shift key or Ctrl key? According to `keyboard.xml` in fgdata, using Shift would cause you to look in a certain direction (front or back, one of those), but it doesn't work here. So we could use the Shift key.

**Comment by gilbertohasnofb** [comment] 2015-06-29 00:56
> What do you think of having coarse + fine throttle/mixture control? 

Sounds good to me. But since the mixture is already controlled by `m` and `Shift+M`, then using the Shift key for the fine adjustments may be complicated.

**Comment by onox** [comment] 2015-07-08 07:45
@wkitty42 The throttle change rate is just different now, so I think you just need to adapt to it. Instead of pressing PageDown 10 times, you press it 3 times.

**Comment by wkitty42** [comment] 2015-07-08 13:04
On 07/08/2015 03:45 AM, onox wrote:
> @wkitty42 <https://github.com/wkitty42> The throttle change rate is just
> different now, so I think you just need to adapt to it. Instead of pressing
> PageDown 10 times, you press it 3 times.

how do i recover the other 7 granularity pieces for each of the ten step 
sections? or all the other steps that are inaccessible now on the throttle 
scale? sure, you made it faster for you but less precise for others... setting 
an exact speed is harder/next to impossible now :(

**Comment by onox** [comment] 2015-07-08 18:00
There are about 90 - 100 steps (key pressed) to go from 0 to 1, that should be more than sufficient.

**Comment by onox** [comment] 2015-07-08 18:21
"throttle control keys are too coarse" is a bit nonsense IMO. The old behavior gives a delta of always 0.01. The new behavior uses 1.0 * `controls.THROTTLE_RATE` * /sim/time/delta-realtime-sec, which means that `controls.THROTTLE_RATE` can be used to control the sensitivity/speed of the two controls (throttle, and mixture). (It could be exposed to the GUI in the future) So you often get delta's like 0.011 or 0.00825.

I don't think anyone flies like "Set throttle to 100 %, after event X occurs, press 3/PageDown exactly 10 times" or something like that. Once we add failure modes to change the engine in subtle ways, your way of pressing PageUp/PageDown a precise number of times, won't work anymore anyway. You need to look at your instruments and change throttle as necessary.

**Comment by wkitty42** [comment] 2015-07-09 02:39
the main point is that while it was easy enough to set the throttle to eg 87 or 88 or 73... now we cannot as the increments are not the same...

FWIW: i don't understand your formula, either... why is there a time item included??

but whatever, i'll just hack mine back to the standard, normal and original 0.01 and be done with it... at least i'll be able to fly like i have been doing since finding this sim... there is a reason someone set it like that ;)

**Comment by onox** [comment] 2015-07-09 06:36
> FWIW: i don't understand your formula, either... why is there a time item included??

It's supposed to be not affected by frame rate accordingto b2909de in fgdata. See 76a08b64 for incThrottle. I did some more testing and it seems adjusting mixture becomes very fast if frame rate is very low, that's unexpected. Maybe I'll change the throttle back to use +- 0.01, but in that case I'm think about doing the same for the mixture.

> the main point is that while it was easy enough to set the throttle to eg 87 or 88 or 73... now we cannot as the increments are not the same...

FYI You're not giving a clear argument why it needs to be that way.

**Comment by wkitty42** [comment] 2015-07-09 15:57
On 07/09/2015 02:36 AM, onox wrote:
>     FWIW: i don't understand your formula, either... why is there a time item
>     included??
>
> It's supposed to be not affected by frame rate accordingto b2909de in fgdata.
> See 76a08b64 for incThrottle. I did some more testing and it seems adjusting
> mixture becomes very fast if frame rate is very low, that's unexpected.

i must be missing something... my frame rates are no more than 10 and quite 
frequently in the 3 to 5 fps range... i don't see this adjustment problem... am 
i missing something or are others spoiled by high frame rates, processing and 
smoother reactions to their inputs?

> Maybe I'll change the throttle back to use +- 0.01, but in that case I'm
> think about doing the same for the mixture.

the mixture setting i've thought was too coarse, too but just haven't said 
anything about it... it would definitely allow for one to get the best setting 
instead of something approximate...

>     the main point is that while it was easy enough to set the throttle to eg 87
>     or 88 or 73... now we cannot as the increments are not the same...
>
> FYI You're not giving a clear argument why it needs to be that way.

precision is the first thing that comes to mind sans any c0ffee ;)

another thought is the realism factor... these are simple slide controls... 
there are no indents on them to step their settings... if we're on about realism 
elsewhere, we should follow through with realism everywhere as much as possible...

**Comment by onox** [comment] 2015-07-09 17:13
> my frame rates are no more than 10 and quite frequently in the 3 to 5 fps range

That is extremely low. Make sure you hide the menubar and the fps counters in the lower corners of your screen as well (yes, they reduce fps). Instead, click Debug and choose "Cycle On-Screen Statistics", You'll see a white fps counter in the upper left corner that doesn't reduce your fps.

Additionally you can add to `.fgfsrc`:

```
--prop:/sim/rendering/osg-notify-level=fatal
--prop:/sim/rendering/multithreading-mode=CullThreadPerCameraDrawThreadPerContext
--prop:/sim/rendering/draw-mask/clouds=0
```

You can find more settings on the wiki.

**Comment by wkitty42** [comment] 2015-07-09 18:57
i'll try those properties at some point... i think the main thing is that i have a relatively low end video card, though... http://www.newegg.com/Product/Product.aspx?Item=N82E16814130734

**Comment by onox** [comment] 2015-07-10 05:28
That setting (`multithreading-mode`) controls is mostly dependent on your CPU, if your GPU is weak, it doesn't help much.

**Comment by wkitty42** [comment] 2015-07-10 11:28
yeah, CPU is 8-core 4ghz... video is enough to do some programming with and have a half way decent GUI interface if desired... thanks for those settings but have to turn off custom rendering to get 10 fps... average 6-7 with landmass and water maxed...

**Comment by onox** [comment] 2015-07-11 13:20
Anyway, you need a decent amount of fps for FlightGear to run properly. Less than 10 is not sufficient. You may get a lot of jitter in various systems. You should try to lower as many settings as possible to get the highest fps you can get. Hide any windows and text that uses PUI. Make sure you have your video card drivers installed properly and activated. For support on how to get a higher fps, please read the wiki and the forums. This is a bug tracker that should be used for real bugs, not problems caused by using a video card that is just too weak. Therefore I'm going to close this issue. You don't have to respond with a comment to this issue any further.

**Closed by onox** 2015-07-11 13:20 UTC

**Comment by wkitty42** [comment] 2015-07-11 18:07
@onox  i didn't branch the discussion off about frame rates, sir... you did that...

now you've closed this bug but nothing has been said about if this problem with the coarseness of the throttle control (and you mentioned the mixture control, too) is going to be repaired or not :disappointed:
