### ISSUE TITLE
immatriculation/registration/callsign

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#199] opened 2015-05-20 12:54 UTC
the 'default' livery seems to use the callsign as passed via the --callsign=blah option or as filled in the dialogue box... the problem is that it seems to be broken some how and only part of the entered callsign is being displayed in some places... in the pictures below, you can see that the item on the pilot side (left) panel is showing only the 'w' in the same way that it is shown on the external fuselage... the dialogue and the passenger side (right) panel show the callsign as it is entered via the --callsign option... definitely seems to be broken... there's another craft, B1900D or CitationX, that shows this same callsign with no problems... i think it uses the same mechanism that the 'default' livery is using but i don't know enough to be able to verify that :crying_cat_face: 

![fgfs-screen-023a](https://cloud.githubusercontent.com/assets/4641713/7725956/03ded7de-fecd-11e4-9bc1-fd38cab0381e.png)

![fgfs-screen-024a](https://cloud.githubusercontent.com/assets/4641713/7725970/140361fc-fecd-11e4-9a03-1e8a69aa593c.png)

**Comment by gilbertohasnofb** [comment] 2015-05-20 13:06
This is a duplicate of https://github.com/Juanvvc/c172p-detailed/issues/107.

**Closed by gilbertohasnofb** 2015-05-20 13:06 UTC
Labels: bug, duplicate
