### ISSUE TITLE
Landing gear breaks too easily

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#547] opened 2015-11-15 20:49 UTC
According to some users, the landing gear breaks too easy. 

alge wrote:
> So I let my plane site and wait a while was I was eating dinner, tied down and everything. And what do I find when I come back?
![](http://www.pvv.org/~titlesta/auchie.jpg)
> This was with winds "25007KT 210V290" so some gusts but should not be enough to break the nose wheel imho. (:
> 
> ... I might have a bad batch of nosewheels, they seem to be breaking on me all the time. Just taxiing back along a slightly uneven taxiway will do it as well.

@wkitty42 also wrote:
> yeah, this is something that i've run into numerous times with the devel version... i just haven't posted anything on the issue tracker about it yet... i find that if i turn too sharply (like trying to get out of a parking spot at a terminal) or if i'm going a bit too fast while taxiing that i'll hear a quick li'l "squerk" of the rubber chirping and there goes the nose wheel...
> 
> it can also break when tied down and the wind gusts are strong enough... i've watched mine like the front tire off the ground (along with the chocks) and then slam it back down breaking it... most of my testing has been with the weather set to "thunderstorm" or "stormy monday", though...

Personally, I have never broke my gear because of sharp turns (heck, not even on landings it has happened to me, except when landing hard as a rock on purpose to test the effects and sounds).

**Comment by gilbertohasnofb** [comment] 2015-11-15 20:50
alge posted another message, and this one is really interesting:

> Haha, I found my problems with taxiing... It's crashing in the yellow line! *facepalm* Don't know how common it is that we have yellow markings ~15cm above the taxiway. This is EDFM.
> 
> See my gettho video grab at https://goo.gl/photos/PYq46H6yGTaHaby57 - complete with portrait orientation to be extra annoying.
> 
> Maybe there's a quickfix for that, by turning off hit detection on taxi/runway markings.

His video shows very clearly the problem with the taxiways. Has any of you experienced anything similar? (also, a note about the video link: for some reason I can't watch it directly on my browser, but I could download and watch it using my video player)

**Comment by wkitty42** [comment] 2015-11-15 23:26
On 11/15/2015 03:49 PM, Gilberto Agostinho wrote:
> @wkitty42 <https://github.com/wkitty42> also wrote:
>
>     yeah, this is something that i've run into numerous times with the devel
>     version... i just haven't posted anything on the issue tracker about it
>     yet... i find that if i turn too sharply (like trying to get out of a
>     parking spot at a terminal) or if i'm going a bit too fast while taxiing
>     that i'll hear a quick li'l "squerk" of the rubber chirping and there goes
>     the nose wheel...

yeah, i broke mine the other day taxiing around KSFO at ~20kts or so... i wasn't 
really even turning very hard, either...

i've also broken it trying to spin in the parking place so i could get out to 
the runway since we don't have pushback for the c172p... in this case, i held 
the right or left brake and ran the throttle up at least 80% and back down to 
try to get some movement and turning so i could go ahead and taxi out... i 
realized that something was wrong when i didn't see the prop shadow from it 
spinning... when i popped out to the heli view, i saw the front gear was broken 
and the prop was all bent up and not spinning even though the engine (180HP) was 
still running like normal...

**Comment by wkitty42** [comment] 2015-11-15 23:28
On 11/15/2015 03:50 PM, Gilberto Agostinho wrote:
> alge posted another message, and this one is really interesting:
>
>     Haha, I found my problems with taxiing... It's crashing in the yellow line!
>     /facepalm/ Don't know how common it is that we have yellow markings ~15cm
>     above the taxiway. This is EDFM.
>
>     See my gettho video grab at https://goo.gl/photos/PYq46H6yGTaHaby57 -
>     complete with portrait orientation to be extra annoying.
>
>     Maybe there's a quickfix for that, by turning off hit detection on
>     taxi/runway markings.
>
> His video shows very clearly the problem with the taxiways. Has any of you
> experienced anything similar? (also, a note about the video link: for some
> reason I can't watch it directly on my browser, but I could download and watch
> it using my video player)


that may very well be what i got caught on since i was using the "'" AIATC stuff 
and following the groundnet lines out to the runway...

i haven't tried to look at the video yet as i'm responding to these from my 
email instead of on the web...

**Comment by wlbragg** [comment] 2015-11-16 00:02
>Has any of you experienced anything similar?

I have noticed on some airstrips that that yellow line is excessively high above the ground.

**Comment by wkitty42** [comment] 2015-11-16 00:37
On 11/15/2015 07:02 PM, wlbragg wrote:
>     Has any of you experienced anything similar?
>
> I have noticed on some airstrips that that yellow line is excessively high above
> the ground.


personally, i think that the main thing is that these lines should not be "hot" 
(aka damaging)... is this something that needs be taken care of upstream (aka 
with the fgfs core developers)???

**Comment by wkitty42** [comment] 2015-11-16 00:48
On 11/15/2015 07:02 PM, wlbragg wrote:
>     Has any of you experienced anything similar?
>
> I have noticed on some airstrips that that yellow line is excessively high above
> the ground.


this may not be the same thing but i'm sharing it anyway...

i'm at KSFO in parking spot D551... i hit the "'" AIATC key and the first thing 
i've done is to hit "2" to turn on the ground net tracks... i haven't even 
started the engine yet but i wanted to show this photo of the ground net track 
roughly knee high to a human...

https://www.dropbox.com/s/hlrc1jsmqr5n2h9/fgfs-screen-090.png?dl=1

i'm fixing to go ahead with the AIATC stuff and see what happens as i taxi out 
to the active runway and get ready for takeoff...

**Comment by wkitty42** [comment] 2015-11-16 01:09
i don't know why my last post isn't showing the photo unless it is because i did it in email... but i think i've found part of my problem...

as i have only the keyboard which i fly with, using differential braking also requires that you steer the nose wheel with the INS and KP-ENTER keys... using any enter key causes dialog boxes to go away or send their default like when using the AIATC... so someone, probably me, needs to figure out a decent set of keys to use for turning the nose gear without mucking everything else up... this, the key conflicts, is a real problem that really should be taken care of at a higher level (aka the core developers)... there really should be a way to detect the difference between the KP-ENTER and the normal ENTER keys so that things like this don't wreck stuff :(

**Comment by onox** [comment] 2015-11-16 05:21
So the yellow line thing is something to be fixed in FG/FGData. And the nosewheel breakage is probably that JSBsim property that we used a short while ago.

@gilbertohasnofb Whenever someone has a problem, can you ask them the specific commit/revision of our project they are using? They can do `git log` and check the commit ID of the uppermost commit, or do `git rev-parse HEAD`.

**Comment by gilbertohasnofb** [comment] 2015-11-16 10:43
About the yellow line, Thorsten wrote:

> I can't rule out that there's the one or other odd line that's displaced in the mesh somewhere, but to visually see them displaced if you're looking carefully is very common and without side effects.

And I think he is right, I have never seen any problems with the yellow line and other airplanes. 

@onox wrote:

> Whenever someone has a problem, can you ask them the specific commit/revision of our project they are using? They can do git log and check the commit ID of the uppermost commit, or do git rev-parse HEAD.

Ok, I will start asking that, but I am afraid most people using our plane are not using git but rather downloading the zip file from GitHub. Anyway, I will ask alge.

@wkitty42 wrote:

> yeah, i broke mine the other day taxiing around KSFO at ~20kts or so... i wasn't really even turning very hard, either...

I think 20 knots is extremely fast for straight taxi, not to mention turning. Taxi is a very slow process in RL.

> i've also broken it trying to spin in the parking place 

Oh well, it's a Cessna 172, not a Mercedes F1 W06 :wink:

**Comment by dany93** [comment] 2015-11-16 10:54
>as i have only the keyboard which i fly with, using differential braking also requires that you steer the nose wheel with the INS and KP-ENTER keys...  ....so someone, probably me, needs to figure out a decent set of keys to use for turning the nose gear without mucking everything else up... 

In the mode "Mouse is controlling flight controls", a left click (held pressed) enables you to control the rudder, thus the nose wheel to steer the aircraft on the ground.  Why don't you use this?
I know that you have not much room on your desk, but my mouse setting is such that I sweep from one side of the screen to the other in a bit less than 3 cm and that's accurate enough to steer the aircraft on the ground. For rolling and up to taking off.

**Comment by gilbertohasnofb** [comment] 2015-11-16 14:55
@onox alge wrote in the forum:

> This is 53e0bdf5 from master.

**Comment by onox** [comment] 2015-11-16 18:28
If he can reproduce it again when tied down, let him try to sit the aircraft idle for a while **without** being tied down or chocks, but **with** the parking brake on. Behavior should be the same, because that's all we're doing: secretly applying the parking brake.

**Comment by onox** [comment] 2015-11-16 18:29
And put the aircraft somewhere where there are no yellow/white lines.

**Comment by gilbertohasnofb** [comment] 2015-11-16 22:21
Okay, I will write that to him (right now the forum is down).

**Comment by onox** [comment] 2016-01-09 21:39
Is this still an actual issue?

**Comment by wlbragg** [comment] 2016-01-10 05:57
If you ever tried to land the Shuttle, there is no such thing as "too easy". I don't notice it as being easy, unless there is a specific action or an exact circumstance that makes it break real easy.

**Comment by onox** [comment] 2016-01-10 12:00
> His video shows very clearly the problem with the taxiways. Has any of you experienced anything similar?

I can reproduce it on the taxiway near runway 27 at EDFM:

![fgfs-screen-413](https://cloud.githubusercontent.com/assets/3361585/12221376/f8b6e42a-b798-11e5-80f3-8dbfe3e77e2f.png)

But as Thorsten said; that's an issue with the scenery mesh.

About the nose gear damage: I can only barely reproduce it with strong tail winds of more than 40 knots, but at that speed the wings have a tendency to get lifted in the air.

I can reproduce it sometimes when taxiing. Currently the nose gear force is 1500 N, which is a bit (too) close to values like 1200 that you get during braking. We can increase it a bit, but I remember having much discussions with @dany93 about that 1500 value :wink: If he's ok with it, we could increase it to 1600 or 1700.

**Comment by dany93** [comment] 2016-01-10 13:23
@onox 
From your description (and my opinion, based on my tests when we adjusted it), the nose gear is not that easy to break. The risk is having it too hard, as @tigert  wrote it at this time.
However, that is only my opinion and the damages have been firstly implemented by @wlbragg and you. I do not feel to have the right (nor the practice IRL) to be "opposed".

**Comment by onox** [comment] 2016-01-10 15:14
In that case we should leave the force as it is.

Shall we close this issue and add a "wont fix" label to it?

**Comment by wlbragg** [comment] 2016-01-10 15:25
For now, :+1:

**Closed** 2016-01-10 15:35 UTC
Labels: bug, FDM, wontfix

**Comment by dany93** [comment] 2016-01-11 22:38
After thinking, the nose wheel is really fragile. On ultralights, we hold the stick fully pulled when taxiing to decrease the load on it. Also, we pull the stick during acceleration before takeoff, just enough to almost have it not touching the ground.
At landing, the nose wheel must never ever touch first or even at the same time as the main wheels.
