### ISSUE TITLE
instrument lights shouldn't be functioning when master is off

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#103] opened 2015-03-24 15:52 UTC
Currently, ~~all lights (strobe, beacon, nav, landing and instrument lights)~~ ~~some lights (landing and instrument lights)~~ the instrument lights work even when the master is off.

**Comment by onox** [comment] 2015-03-24 17:45
I cannot reproduce this. If I turn off the battery master, then the lights turn off.

**Comment by gilbertohasnofb** [comment] 2015-03-24 20:35
@onox Hmm, I tested it again and I don't know how I managed to make this bug appear the first time! Now the strobe, beacon and nav lights are working properly, so either I got confused or this is a bug that needs more steps to reproduce.

But the instrument lights are still working when master switch is on, and the landing lights as well (I use ALS). Can you try to reproduce these two?

**Comment by onox** [comment] 2015-03-24 21:31
Yes, instrument lights still works if master switch is off and ALS landing light too.

**Comment by gilbertohasnofb** [comment] 2015-03-24 21:39
thanks!

**Comment by gilbertohasnofb** [comment] 2015-03-27 21:32
UPDATE: I found how to reproduce the strobe, beacon and nav lights being on while the master is off. Simply turn the master on, turn the lights on, reset the simulator. The aircraft will be reloaded with the master off (good decision), light switches (good) on and all lights will be visible (bug!), as if the battery would be on!

**Comment by wlbragg** [comment] 2015-03-29 05:58
This is probably a different problem but may be related. I don't know when this crept in or for sure if it is wrong, but I think it is.
When I start the sim the all the lights are on including the strobes, except the strobes are on solid, not blinking.

**Comment by gilbertohasnofb** [comment] 2015-03-29 06:01
@wlbragg I am away from my computer now (which has FG installed on it), but I guess what you are describing is exactly identical to what I was experiencing. So there are basically two issues here:

- initial state of nav, strobes and beacon lights is on even though master is off
- functioning  landing lights and instrument lights when master is off

**Comment by onox** [comment] 2015-03-29 12:25
The problem appears to be that `/sim/model/c172p/lighting/strobes/state` is somehow `true` after initialization. I could not find anywhere in the code where this could be happening. The only thing that controls this boolean is the `aircraft.light` class. When I added `debug.dump()` calls to the `light` class in `Nasal/aircraft.nas` I noticed that `state` was first `0`, and then later after JSBSim had printed some statistics, it had somehow become `1`, even though I did not see any of my debug statements being printed on lines where it might possibly set `state` to `1`.

So the only place where `state` was referenced, was during the aliasing of the `multiplay/generic/` properties in `c172p-detailed-set.xml`. Apparently this causes the two `state` properties to receive the values from the MP properties (casted to booleans). I have not seen this behavior happening before in other aircraft, but writing a 0 to the two `state` properties in `Nasal/electrical.nas` seems to have fixed it for me.

Fix added in pull request #112.

**Comment by gilbertohasnofb** [comment] 2015-03-29 14:09
- ~~initial state of nav, strobes and beacon lights is on even though master is off~~
- functioning landing lights and instrument lights when master is off

Half of this issue was indeed solved by the pull request https://github.com/Juanvvc/c172p-detailed/pull/112, still missing the ALS landing lights and instrument lights issue.

**Comment by onox** [comment] 2015-03-30 01:14
Reopening issue because of the ALS landing light and instrument lights.

**Comment by gilbertohasnofb** [comment] 2015-03-30 01:16
Did I close this issue myself?! I must be going crazy, I don't recall doing that at all.

**Comment by onox** [comment] 2015-03-30 03:18
No it was closed automatically by Github because I referenced it in a commit that got merged by the PR.

**Comment by gilbertohasnofb** [comment] 2015-03-30 08:25
I see

**Comment by onox** [comment] 2015-04-21 13:51
Pull request #122 fixes the ALS landing light, but not the instrument lights.

**Comment by gilbertohasnofb** [comment] 2015-06-06 18:44
Now that we have the ALS lantern, could we try to fix this? Should be just some few lines of code, right?

**Comment by onox** [comment] 2015-06-06 21:58
We need to modify the bindings of keys L and shift+L and change the dial on the panel to not adjust `/sim/model/material/instruments/factor` but a new property. This new property needs to have its value propagated to `/sim/model/material/instruments/factor` depending on the voltage of the electrical bus.

**Comment by gilbertohasnofb** [comment] 2015-06-06 22:00
Oh, okay onox. I don't know how much work this is, but it's certainly more than I thought. My idea was simply to make some sort of conditional such as: if master off then force instrument lights off, else apply value from instrument lights dial.

**Comment by wkitty42** [comment] 2015-06-06 22:06
don't the instrument lights go through the electrical system and the circuit breakers? aren't they controlled by the master switch? i/we will need to look at the schematics again... now where'd that pdf file go?

**Comment by gilbertohasnofb** [comment] 2015-06-06 22:28
@wkitty42 do you mean this one?: http://s18.postimg.org/n12yt1qk9/Screenshot_from_2015_03_13_17_33_45.png

Yes, they do go through the elec system and circuit breakers (look for INT LT)

**Comment by wkitty42** [comment] 2015-06-06 23:12
yep! that's the one we've seen before... i note that the dome, courtesy and map (on the door post, not modeled in this craft yet??) lights are on the same circuit breaker and everything is controlled by the master switch... but that switch is actually two switches, right? battery and alternator... ok... yeah, if both master switches are off, then no lights should work at all... except the new ALS flashlight which we'd use to find the battery switch in the dark to enable the dome, courtesy and map lights if needed before getting everything started...

in the case of this report, it would seem to be a matter of tying the instrument lights to their circuit breaker which should already be tied to the power buss... right?

**Comment by onox** [comment] 2015-06-07 00:35
@gilbertohasnofb Hmm.. I see L and shift+L already control a separate property `/controls/lighting/instruments-norm`. But something is then adjusting `/sim/model/material/instruments/factor` :confused:

**Comment by gilbertohasnofb** [comment] 2015-06-07 00:38
Yeah, I believe what you wrote is correct. About the masters, I believe this is how they work:

Battery ON, Alternator OFF, Engine OFF: electricity is available but drained from the battery
Battery ON, Alternator OFF, Engine ON: electricity is available but drained from the battery
Battery ON, Alternator ON, Engine OFF: electricity is available but drained from the battery
Battery ON, Alternator ON, Engine ON: electricity is available and battery is recharged
Battery OFF, Alternator OFF, Engine OFF: no electricity available
Battery OFF, Alternator OFF, Engine ON: no electricity available
Battery OFF, Alternator ON, Engine OFF: no electricity available
Battery OFF, Alternator ON, Engine ON: electricity available (I believe!)

**Comment by gilbertohasnofb** [comment] 2015-06-07 00:39
@onox do you know any other key that is free? We can add this to the aircraft help. What about F and Shift+F (for flashlight)?

**Comment by onox** [comment] 2015-06-07 00:44
F and Shift+F are free. You can check that in `keyboard.xml` in fgdata :smile:

**Comment by gilbertohasnofb** [comment] 2015-06-07 00:45
Cool! So let's go for it :)

**Comment by onox** [comment] 2015-06-07 00:46
I found the relation, it's in `Nasal/light.nas` :stuck_out_tongue_closed_eyes:

**Comment by onox** [comment] 2015-06-07 00:50
I think we can use the same trick as for the ALS lights; just add a `<logic>` element to `Systems/als-lights.xml`. Could you do this @gilbertohasnofb? Do it in a separate branch with `git checkout -b bug-103-instruments` (`bug-103` itself is already taken) so I can review it :smile:

**Comment by onox** [comment] 2015-06-07 00:51
Or create a new issue, because I abused bug-103 for the ALS lights.

**Comment by gilbertohasnofb** [comment] 2015-06-07 00:56
@onox sorry but this is beyond my knowledge, onox. I know near-to-nothing of xml..

**Comment by tigert** [comment] 2015-06-07 01:32
The c172 Pilots Operating Handbook has a electronics schematic. We should model the electric buses and check them for power availibility (and see where each breaker is wired to) sothat the logic is implemented just once. 

I can try to look into this too but currently a bit restricted in free time for a week or two, so it might be a bit slow for a bit.

**Comment by onox** [comment] 2015-06-07 01:46
@tigert We are already doing that. Check `Nasal/electrical.nas`.

**Comment by onox** [comment] 2015-06-07 01:48
I'll do this then. Should be easy.

**Comment by gilbertohasnofb** [comment] 2015-06-07 01:49
Thanks and sorry about it.

**Comment by onox** [comment] 2015-06-07 02:13
@gilbertohasnofb When you press Ctrl+C, the names of "Autopilot" and "DME" are reversed.

**Comment by gilbertohasnofb** [comment] 2015-06-07 02:18
@onox confirmed, just opened a new issue for that: https://github.com/Juanvvc/c172p-detailed/issues/256

**Comment by onox** [comment] 2015-06-07 02:23
@gilbertohasnofb The PR is waiting for you, do `git fetch` and `git checkout bug-103-instruments` to test it.

**Closed** 2015-06-07 02:27 UTC
Labels: animations (XML), bug, procedures
