### ISSUE TITLE
new pitot tube and pitot tube cover models by D-ECHO

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#541] opened 2015-11-13 18:08 UTC
See what you guys think: http://forum.flightgear.org/viewtopic.php?f=4&t=25157&sid=e0003120d18c3dbd64377a5b75f57af7&p=264380#p264380

Although the model is "richer" than ours, it doesn't look like any RL model I've seen in pictures. What are your opinions?

**Comment by wlbragg** [comment] 2015-11-13 18:14
Do you know if the @thevirtualfer has done anything with the pitot tube in his work?

**Comment by gilbertohasnofb** [comment] 2015-11-13 18:17
@wlbragg I've got not idea about his work at all, he didn't commit anything in months and it also has been a while since the last time he posted pictures. My guess is that he probably improve the tube, so it's up to us to either wait for him (which may take months) or incorporate this. I personally think that his tube is better than ours, but I am not very happy with his cover for the reasons I wrote above.

**Comment by gilbertohasnofb** [comment] 2015-11-13 18:43
D-ECHO wrote in the forum:

> I've based the cover on one a friend uses on his DR400-135CDI/140B

**Comment by wlbragg** [comment] 2015-11-13 19:02
Yeah, I'd prefer we stick with something the c172p uses in RL.

**Comment by gilbertohasnofb** [comment] 2015-11-13 19:28
Me as well. As I posted in the forum, the two most common pitot tube covers I've seen in pictures of 172 are by far these two:

![image1](http://static.panoramio.com/photos/large/37348192.jpg)

![image2](http://www.sportys.com/media/catalog/product/9/6/9651_4.jpg)

Of course not counting the most common of them all:

![image3](http://portfolioticker.com/wp-content/uploads/2015/06/pitot_tube_cover.jpg)

:wink: 

I'd say our current cover looks pretty similar to the second one, so even though there is a huge room for improvement with that model I'd still prefer to keep it, so I guess we are clear with this. As for the pitot tube itself, if it isn't so much trouble we could incorporate his, ours is __very__ low-poly at the moment.

**Comment by onox** [comment] 2015-11-15 12:41
It looks a bit like in [this YouTube video](https://www.youtube.com/watch?v=dqCqHlAn3b0&t=228)

**Comment by gilbertohasnofb** [comment] 2015-11-15 12:45
Yes, I think that's an identical model indeed. So what do you guys think, should we use this new model? I personally feel that it's more detailed, but I kind of prefer ours. But it's up to you all, I am fine with either one.

**Comment by onox** [comment] 2015-11-15 14:21
Is this a duplicate of #492?

**Comment by gilbertohasnofb** [comment] 2015-11-15 14:30
It's not exactly a duplicate, this is rather a question. If we say yes, it does close indeed #492, but if we say no then we close this issue but leave that other one opened for future improvements.

**Closed** 2016-01-12 21:06 UTC
Labels: 3D model, enhancement, question
