### ISSUE TITLE
Error message: sound volume too large for cough

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#776] opened 2016-05-30 21:49 UTC
I'm seeing a lot of these. A lot is a really really large number scrolling by. Not just a couple a second but a lot. This might be because I'm at 15000 ft, throttle wide open, 95 kt IAS, 138 kt GS. I don't know but the engine (180HP) sounds like it normally does. I'm just seeing these flying across the console.

```
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
Sound volume too large for 'cough':  1.30002  ->  clipping to 1.0
```

**Comment by onox** [comment] 2016-08-08 20:40
@wkitty42 Is it just the 'cough' sound or other sounds as well? (Please give a list of the sounds which are clipped in that case)

**Comment by wkitty42** [comment] 2016-08-08 21:26
On 08/08/2016 04:40 PM, onox wrote:
> @wkitty42 Is it just the 'cough' sound or other sounds as well? (Please give
> a list of the sounds which are clipped in that case)


TBH i don't know... i can't say that i've ever heard the engine coughing at all 
but i've seen the notice on the console... i don't know if the clipping report 
is for just the one sound or all of them added together...

i'm guessing that the sound is coughing.wav from FGDATA... i don't find a 
specific one in our sounds directory... i just went and played the one in FGDATA 
with audacity and it sounds almost like the sound when trying to start the 
engine... when i've seen the coughing notice, it was when i was flying and way 
up around 12500 with max throttle and the mixture pulled back enough to give me 
max RPMs... i don't know when that sound was started to be played, though... i 
had just happened to ALT-TAB to the console to see what was going on because i 
was being nosy when i first saw it...

i have adjusted my update routine so that every time i update fgfs, fgdata and 
terrasync, i also update the c172p from the dev repo so i have the latest master 
branch all the time now... that's the only one i fly when i fly the c172p :)

**Comment by onox** [comment] 2016-08-08 21:31
The coughing sound is heard when the engine starts.

**Comment by wkitty42** [comment] 2016-08-09 18:50
i'll try looking again... since i'm ensuring the craft is updated every time i update my fgfs, it may be fixed already...

**Comment by gilbertohasnofb** [comment] 2016-08-10 08:11
The cough is also heard when the oil level is just above critical I believe. 

@wkitty42 just to make it clear, do you still see those error messages? I don't see them here at all.

**Comment by wkitty42** [comment] 2016-08-10 17:46
On 08/10/2016 04:11 AM, Gilberto Agostinho wrote:
> The cough is also heard when the oil level is just above critical I believe.

how do i check that?

> @wkitty42 just to make it clear, do you still see those error messages? I
> don't see them here at all.

i have to wait until the devs fix the NaturalEarth compilation failure... i'll 
test it as soon as that happens and i can build fgfs and all its tools again :(

**Comment by wkitty42** [comment] 2016-08-12 13:00
ok, finally got fixed fgfs sources and can test...

removed tie-downs and chocks, used autostart and took off from St. Barts (TFFJ) using the big engine (180HP??)... am at an altitude of 5000 feet, throttle is set to 88%, mixture at 91%, airspeed is 120 kts... headed to Miami (KMIA)... almost an eight hour flight... i'm still seeing tons and gobs and gobs and tons of 

Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
loadxml: failed to find airport data for Path "jetways.xml" at ICAO:TQPF
loadxml: Failed to open file
 at /home/myuser/flightgear-dev/fgdata-ng/AI/Airports/TQPF/jetways.xml
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0

scrolling by when i ALT-TAB to the console... i have no clue if i'm doing something wrong or not... the engine sound sounds like it always has... i can't hear any coughing in it at all... note again that i'm using the big engine and not the smaller/original one... standard landing gear, wheels with pants...

**Comment by gilbertohasnofb** [comment] 2016-08-12 13:03
@wkitty42 is it relevant that the flight was 8h? I.e. does this error appear after hours of flying ro does it appear as soon as you load the sim? It would be great if there was a way of reproducing it in a _muuuch_ shorter flight :wink:

**Comment by gilbertohasnofb** [comment] 2016-08-12 13:22
I tried making a flight with the 180 HP, and I even induced some coughing on the engine using low oil levels but I see no errors

@wkitty42 BTW can you please post a picture of your settings in the dialog File > Sound Configuration just out of curiosity?

**Comment by wkitty42** [comment] 2016-08-12 14:28
On 08/12/2016 09:03 AM, Gilberto Agostinho wrote:
> @wkitty42 is it relevant that the flight was 8h?

no, i was just saying... that's all...

> I.e. does this error appear after hours of flying ro does it appear as soon
> as you load the sim?

it could start while i'm on the ground... i've not looked because i've been too 
busy taking off :lol:

> It would be great if there was a way of reproducing it in a /muuuch/ shorter
> flight 😉

i don't understand why you guys can't reproduce it... i'm using the master 
branch of the craft and that's pretty much all i ever use... i'll stop the 
flight and start again and see if i can reproduce the problem on the ground 
before taking off...

FWIW: i have full --log-level=debug logs but this isn't logged in the log file 
as i'd expect debug level logs to do :(

**Comment by gilbertohasnofb** [comment] 2016-08-12 14:33
> FWIW: i have full --log-level=debug logs but this isn't logged in the log file as i'd expect debug level logs to do :(

A-ha! So that's not visible on the alert mode (which I believe is the default). Ok, so in debug mode I get a trillion million messages, and indeed I am able to see these as soon as I start the engine:

```
[...]
Sound volume too large for 'engstart':  1.1143  ->  clipping to 1.0
Sound volume too large for 'crank':  1.2143  ->  clipping to 1.0
Sound volume too large for 'engstart':  1.1143  ->  clipping to 1.0
Sound volume too large for 'crank':  1.2143  ->  clipping to 1.0
Hobbs system started
Sound volume too large for 'engstart':  1.1143  ->  clipping to 1.0
Sound volume too large for 'crank':  1.2143  ->  clipping to 1.0
Starter off
Sound volume too large for 'engstart':  1.1143  ->  clipping to 1.0
Stopping audio after 2.09167 sec: crank
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Playing audio after 13.175 sec: cough
Playing once
Playing audio after 13.175 sec: engine
Playing looped
Sound volume too large for 'engstart':  1.1143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
Sound volume too large for 'cough':  1.0143  ->  clipping to 1.0
[...]
```

@onox it looks like indeed our volumes are a bit messed up. Should we try fixing this or since we are happy with the resulting sound we can just live with the clipping (FG is basically taking care of it for us) and make this a "won't fix"?

**Comment by gilbertohasnofb** [comment] 2016-08-12 14:35
@wkitty42 thanks for the patience and for the tests and reports, by the way. Sometimes little things make something not be reproducible in other computers, and it's maddening when we are seeing something that others don't :smile:

**Comment by wkitty42** [comment] 2016-08-12 14:50
On 08/12/2016 09:22 AM, Gilberto Agostinho wrote:
> I tried making a flight with the 180 HP, and I even induced some coughing on the
> engine using low oil levels but I see no errors

i have full oil and full clean fuel...

> @wkitty42 BTW can you please post a picture of your settings in the dialog
> File > Sound Configuration just out of curiosity?

my sound device is "Built-in Audio Analog Surround 4.1".

Master volume is at 50%-60%.

all others are "enabled" (Xed) and set to 75%.

turning each down and back up does not affect the console reporting of the 
coughing being clipped.

OH!! OH!! OH!!

turning off (unXing) the Master does stop the reporting of the clipping.
turning off (unXing) the Effects does stop the reporting of the clipping.

after turning off (unXing) and back on (Xed) the Effects volume, my sound has 
changed in the Chase view. now i just hear the wind blowing by. switching to the 
cockpit view gives me the engine sound again. cycling through all the views 
keeps the engine sound with the clipping notices. turning off and on the Effects 
does this each time.

i get the same thing with the Master when i turn it off (unXed) and back on (Xed).

in the Helicopter view, the sound gets louder and softer as i use the mouse 
button to scroll closer and further away from the craft. it doesn't do this in 
the Chase view as i can't scroll closer and further to/from the craft.

i really really don't have any clue why the coughing sound would still be being 
played once the engine is started and there's no other triggers (low oil, water 
in the fuel, too high RPMs, etc) that would cause it to cough...

i still have to start the flight over and see if maybe i can see this while just 
sitting on the ground and maybe even still tied down as if doing an engine RPM 
run up/down test...

**Comment by wkitty42** [comment] 2016-08-12 15:00
On 08/12/2016 10:33 AM, Gilberto Agostinho wrote:
>     FWIW: i have full --log-level=debug logs but this isn't logged in the log
>     file as i'd expect debug level logs to do :(
>
> A-ha! So that's not visible on the alert mode (which I believe is the default).
> Ok, so in debug mode I get a trillion million messages, and indeed I am able to
> see these as soon as I start the engine:

YESSSS!!! that's what i was just coming back to report that i see it as soon as 
i start to crank the engine...

> @onox it looks like indeed our volumes are a bit messed up. Should we try
> fixing this or since we are happy with the resulting sound we can just live
> with the clipping (FG is basically taking care of it for us) and make this a
> "won't fix"?

personally, i'd fix them but for the next release... no way to try to fix this 
now this close to tagging a release version to go with 2016.3...


FWIW: i didn't realize that some of these messages don't show up in other 
logging modes... i /always/ run in debug mode and 99% of the time in the 
debugger (gdb) too...

**Comment by wkitty42** [comment] 2016-08-12 15:02
On 08/12/2016 10:35 AM, Gilberto Agostinho wrote:
> @wkitty42 thanks for the patience and for the tests and reports, by the way.
> Sometimes little things make something not be reproducible in other
> computers, and it's maddening when we are seeing something that others don't
> 😄


not a problem... all i can do is to report what i see and try to give as much 
detail as i can... some things, like my logging level, just don't come to 
mind... especially when they're my default :wink: but, yes, i do try as best as 
i can to describe what i'm seeing :smile:

**Comment by onox** [comment] 2016-08-12 17:11
You can try to modify the `<offset>` parameter for the 3 sounds in `c172-sound.xml`. For example if you see this:

```
Sound volume too large for 'engstart':  1.1143  ->  clipping to 1.0
```

Then you add 1.1143 - 1.0 = 0.1143 to the offset of the sound. So `engstart` needs an additional 0.1143, `crank` needs 0.2143, and `cough` needs 0.0143.

Modify lines 27, 53, and 73.

**Comment by onox** [comment] 2016-08-12 17:19
@gilbertohasnofb You want to fix this for 2016.3 or 2016.4?

**Comment by gilbertohasnofb** [comment] 2016-08-12 17:21
I would rather fix this for 2016.4.

**Comment by onox** [comment] 2016-08-12 17:21
Ok.

**Comment by gilbertohasnofb** [comment] 2016-08-17 15:01
I am fixing this now, I am going to push it very soon

> Then you add 1.1143 - 1.0 = 0.1143 to the offset of the sound. So engstart needs an additional 0.1143, crank needs 0.2143, and cough needs 0.0143.

I think you meant subtract (since the sound is already clipping, adding to an offset makes it worse). But yes, I get the idea :+1:

**Comment by onox** [comment] 2016-08-17 16:47
> I think you meant subtract

Yes, sorry, meant subtracting.

**Closed** 2016-08-17 16:48 UTC
Labels: animations (XML), bug, sound
