### ISSUE TITLE
drifting on runway...

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#297] opened 2015-06-14 22:05 UTC
i don't know what's happened but as of commit 7b5004ff32e8983a365cd8624b5ccd9248969ee1 i'm drifting on the runway (or taxiway) when i'm completely powered down and have the brake set... in fact, i first noticed this because just starting the sim, i always set the brake and the craft settles nose down as if the brakes are being applied during landing or rolling... if i release the brake, the nose of the craft rises... set it again and the nose goes down... you can see this from heli view beside the craft... it is like the nose wheel is kneeling in prayer or something...

so while looking at the above (another issue??) from heli view, i noticed that we're drifting on the runway... brakes on or off, doesn't matter... almost like when we first got the pontoons but i'm using normal gear and not pontoons right now... i don't think this is related to wind because the windsock is pointed out to my right (at KMCO) so the breeze should be from my left to my right but the drift i'm seeing is forward down the runway and not sideways at all...

i need to try to get something set up so i can record this stuff :(

**Comment by onox** [comment] 2015-06-15 03:23
Which bushkit option were you using?

**Comment by onox** [comment] 2015-06-15 03:26
What is the weather like (wind speed) when the problem occurs?

**Comment by wkitty42** [comment] 2015-06-15 09:30
ummm... the drifting didn't appear to be with the wind... there is some windmilling at times on the amphibious pontoons when sitting on the runway but when i wrote the original issue, the drifting was straight down the runway... very very slowly, though... it took like maybe 30 minutes to drift from the back of the broad white lines on the end of the runway to the front of them... what is/was confusing is that the windsock was flipping off to the right as noted previously... not standing out straight but sideways from me and not pointing in the direction i was drifting...

i'm not seeing any drift right now... i found /environment/wind-* and they're all reading '0' right now... if/when it happens again, i'll try to remember how to get to these and take a look...

i'm also not getting that weird kneeling thing when i set and unset the parking brake either... that's just too weird... could it be that these happened because i loaded the original c172p to get a snapshot of the DME toggle switch? this goofiness started happening after i did that and switched back over to this craft... i simply chose them from the --launcher screen... the original is still in my fgdata and this one is in my custom craft directory...

**Comment by gilbertohasnofb** [comment] 2015-07-13 09:17
Same as 307: is this issue still relevant or can I close it? If still relevant then I will add labels and a milestone (3.8) to it.

**Comment by wkitty42** [comment] 2015-07-15 04:08
i still see this from time to time... not as noticeable as it was but i see it with and without pontoons now whereas when it was first reported, it was with pontoons only and that was before the hydro FDM was imported IIRC... you'll have to forgive me as i catch up on 36+ hours of posts after some sever storm damage over here that's already cost us two machines :crying_cat_face:

**Comment by wlbragg** [comment] 2015-07-15 04:28
@wkitty42, we had a system move through here last week that put me on the generator for about 12 hours. Buying our generator was one of the best investments I ever made!
It has saved me more times than I can count now.

**Comment by wkitty42** [comment] 2015-07-15 04:54
@wlbragg we've had a generator since hurricane fran came through... we didn't need it this time but yeah, i know the feeling... camping when you choose to is one thing... being forced to is quite another... but i'll stop on this side track now... don't wanna upset the gendarmes more than they already are :(

**Comment by gilbertohasnofb** [comment] 2015-07-15 11:31
@wkitty42 
> after some severe storm damage over here that's already cost us two machines 

Sorry to hear that!

> i still see this from time to time... not as noticeable as it was but i see it with and without pontoons now whereas when it was first reported, it was with pontoons only and that was before the hydro FDM was imported IIRC... 

Do you think you can try to reproduce this bug once your computer is working properly again? I tried reproducing it here but I couldn't, parking brakes and pontoons = aircraft stopped in the runway.

**Comment by wkitty42** [comment] 2015-07-15 17:26
i will try to test more, yes... it was my firewall and main bbs/mail/web server that got hit... have the firewall back up... working on the other now... fingers crossed...

**Comment by wkitty42** [comment] 2015-07-15 17:57
yes, i am still seeing this... i run in full screen mode so it is easy for me to see...

i just started at KSFO, on runway 10L, live METAR with normal landing gear... i switched to pontoons, not amphibious... i have not done any startup tasks at all so we're sitting dead draining the battery... i'm seeing windmill drifting... 10L actuall heading is ~117 degrees straight down the centerline according to the HUD... i'm windmilling to the left with a 7kt breeze...

wind-from-down-fps = 0.000323xxxxx
wind-from-east-fps = 11.861xxxxxxxxx
wind-from-heading-degree = 90.066xxxxx
wind-from-north-fps = -0.013xxxxxxxx
wind-speed-kt = 7.027xxxxxx

in the few minutes (5?) it has taken me to switch back and forth between the browser and fgfs to get the above numbers, i've windmilled around to ~95 degrees from the original 117 i started at... again, this is with plain pontoons which really shouldn't move at all without some extreme effort and max thrust when on pavement or grass or dirt... i can understand the windmilling and drifting when on water or ice but not on any other surface...

**Comment by gilbertohasnofb** [comment] 2015-11-05 11:28
Is this issue relevant? Has anyone else experienced it? I have never seen it at all...

> i just started at KSFO, on runway 10L, live METAR with normal landing gear... i switched to pontoons, not amphibious...

Why would you change to pontoons on a runway at KSFO??

If the issue is that when you have pontoons you are drifting in a __concrete__ runway, then I'd just close this issue..

**Comment by wlbragg** [comment] 2015-11-05 14:37
Yeah, I'm not sure about this one. 
I can't ever see any conceivable reason in real life a pilot would be in the position of being on the hard surface in floats with no gear out of the gate.
If you ever were to land on your floats on a hard surface it would slide to some extent in wind or forward momentum. Do we want to check for that and adjust the FDM accordingly, can we?

**Comment by wkitty42** [comment] 2015-11-05 15:11
On 11/05/2015 06:28 AM, Gilberto Agostinho wrote:
> Is this issue relevant? Has anyone else experienced it? I have never seen it at
> all...
>
>     i just started at KSFO, on runway 10L, live METAR with normal landing
>     gear... i switched to pontoons, not amphibious...
>
> Why would you change to pontoons on a runway at KSFO??

why does any user of any software do or try to do things that just shouldn't be 
done? remember that i'm coming at this in the guise of "total newbie" and i am 
attempting to do many things that just shouldn't be done specifically to find 
the ones that should not be allowed at all so they can be prevented :+1:

> If the issue is that when you have pontoons you are drifting in a *concrete*
> runway, then I'd just close this issue..

that *was* the issue back then when this was filed :wink:

i believe it has been fixed in the mean time so yeah, we can probably close this 
one, too... it can always be reopened if needed or a new one can be created 
:smile_cat:

**Comment by wkitty42** [comment] 2015-11-05 15:19
On 11/05/2015 09:37 AM, wlbragg wrote:
> Yeah, I'm not sure about this one.
> I can't ever see any conceivable reason in real life a pilot would be in the
> position of being on the hard surface in floats with no gear out of the gate.

https://www.youtube.com/watch?v=Temm5lI-zUI
https://www.youtube.com/watch?v=fg1-whXjKco
https://www.youtube.com/watch?v=jCbZnuiE5Q4

> If you ever were to land on your floats on a hard surface it would slide to some
> extent in wind or forward momentum. Do we want to check for that and adjust the
> FDM accordingly, can we?

i don't know how the above examples got those craft onto the hard surface 
requiring them to takeoff like they do but it is obviously something that comes 
into play at times...

if i remember, though, this was opened because just sitting on the hard surface, 
the craft should not drift and blow around at all... it should behave in similar 
fashion to the brakes being set or possibly even with the new (to use) tie down 
property... unless the winds are storm level (like my stuff the other day at 
KSFO when testing the lightening and thunder sounds and the winds threw my craft 
on top of the terminal building), i don't know that i can see a pontoon craft on 
a hard surface being blown around very much... snatched up and flipped over 
unless tied down, sure... but not just drifting in the wind like on the water 
which i believe was the original issue which i also believe has been fixed but 
i/someone really should to test again to make sure :wink:

**Comment by wlbragg** [comment] 2015-11-05 17:01
>really should to test again to make sure 

Sound like a job opportunity, did you just volunteer to test it? :laughing:

**Comment by wkitty42** [comment] 2015-11-05 17:30
hahaha... in a bit, yes, i do plan to look at this... right now i'm wading through my normal "tasks of the day" in their listed order :wink:

**Comment by gilbertohasnofb** [comment] 2015-11-05 18:55
@wkitty42 

> why does any user of any software do or try to do things that just shouldn't be done? remember that i'm coming at this in the guise of "total newbie" and i am attempting to do many things that just shouldn't be done specifically to find the ones that should not be allowed at all so they can be prevented

I am sorry but I have to completely disagree with you. Your recent posts in this repo are not about bug hunting (which is super beneficial to all of us) but about nitpicking and fussing with utterly unimportant things, and the down side of that is we spend so much time reading and posting in these discussions instead of developing the plane, which is what matters to me. I am absolutely sure that you are able to tell a different between spotting a rare bug and reporting absurd situations. You told me these days that I should implement some conditionals taking into consideration that a plane might be flying with a ground speed of 5 knots if the headwind is 75 knots, for which I say that if someone is stupid enough to worry about removing/adding the pitot cover in that case, then that's my Easter egg for them. Then there is this absurd issue here. Then there is the utterly unimportant rain in the window issue, for which you want a super complex code for a minor visual effect. And then there were tons of other comments trying to convince me not to use Nasal for things we are __already__ using Nasal, and other random guesses about programmin, as for instance when you advised me in the dev list to to add the `<label>` tags inside the `<visible>` tags in my XML code in order to make a text disappear, but you write that without even bothering to check if that's correct -- and so I waste my time checking the absurd proposal. Maybe take some more consideration before posting, see if you are really adding something to the discussion, because lately the sheer volume of "I think"s is raising repidly. I repeat: bug reports are most surely welcome, and so is when you e-mail the devs to find suggestion and then post them back here -- those are things that we all here can appreciate.

> https://www.youtube.com/watch?v=Temm5lI-zUI 
> https://www.youtube.com/watch?v=fg1-whXjKco
> https://www.youtube.com/watch?v=jCbZnuiE5Q4

And I have seen a video in which a cat was hidden inside the wing structure of an ultralight, which lead to the pilot to make an emergency landing, but I don't think any of us are expected to implement these type of stupid ideas. My point is still valid: if an user tried to load a __float__ variant in a concrete runway, then let him/her enjoy the bugs. There are so many more important things to handle here and I can't believe that this issue has been opened for almost half an year and that this discussion is still dragging so much... 

And on top of it all: I just tested this issue by selecting the floats on a concrete runway and with a reasonable weather the amount of movement is __minimal__ (I had to compress time to 32x to observe anything). Now in a thunderstorm it can be seen without time compression, but honestly, if you leave a float plane in a concrete surface without tying it up in the middle of a bloody thunderstorm, then you'd get something exactly like that. So I'd say our "simulation" of a float on concrete surfaces is spot on.

With all that said, I am sorry to say but I am closing this issue.

**Closed by gilbertohasnofb** 2015-11-05 18:55 UTC
Labels: bug

**Comment by wkitty42** [comment] 2015-11-05 23:04
On 11/05/2015 01:55 PM, Gilberto Agostinho wrote:
> You told me these days that I should implement some conditionals taking into
> consideration that a plane might be flying with a ground speed of 5 knots if
> the headwind is 75 knots,

no i did not... i pointed out that it is possible to fly backwards in certain 
situations... nothing more... if you implement a way to cover that, great! 
otherwise, i don't care... it was only a quick little side comment :shrug:

> Then there is this absurd issue here.

it is/was absurd, funny, humorous that it is/was even happening... when 
reported, it was very easily seen in less than 2 minutes... no speeding up time 
or playing other tricks like that... i have just checked again and while i do 
not see the drifting like i did when the issue was first reported, it is still 
happening but at a much slower rate than previously... that may be due to the 
current wind speed, though...

i loaded the sim and had to go do something in RL... when i got back the craft 
was not how i left it... but perhaps i was reading the flight manual or working 
on my flight plan or something similar...

https://www.dropbox.com/s/2xpes500hzmimbt/c172p-20151105-175514.fgtape?dl=0

my live METAR says i have a variable 4kt wind at KSFO right now... i have no 
idea at all what the wind speed was or what direction it was coming from when i 
originally reported this... i'm pretty sure that a lot of code has been 
tightened up in the last four months, though... those additional changes may 
tightened up this issue or not... take it for what it is...

> Then there is the utterly unimportant rain in the window issue, for which you
> want a super complex code for a minor visual effect.

no... i don't /want/ it... i only pointed it out for the realism factor... rain 
running straight down the middle of the door window was quite funny but it took 
away from the otherwise excellent representation of the craft... it you/we want 
the best and to be the showcase craft of the sim, then make the best and cover 
all aspects as best as possible...

> And the n there were tons of other comments trying to convince me not to use
> Nasal for things we are *already* using Nasal,

i'm not trying to convince you... i only pointed out the reason as noted by core 
devs... i don't know what you are using nasal for... i'm aware of some of the 
limitations it has but i'm still learning, too... not too bad for a 50+ year 
old, either...

> and other random guesses about programmin, as for instance when you advised
> me in the dev list to to add the |<label>| tags inside the |<visible>| tags
> in my XML code in order to make a text disappear,

no i did not /advise/ you to do that... i *asked a question* if that was what 
needed to be done...

>     https://www.youtube.com/watch?v=Temm5lI-zUI
>     https://www.youtube.com/watch?v=fg1-whXjKco
>     https://www.youtube.com/watch?v=jCbZnuiE5Q4
>
> And I have seen a video in which a cat was hidden inside the wing structure of
> an ultralight, which lead to the pilot to make an emergency landing, but I don't
> think any of us are expected to implement these type of stupid ideas. My point
> is still valid: if an user tried to load a *float* variant in a concrete runway,
> then let him/her enjoy the bugs.

the point i tried to make by posting those links is to get someone to figure out 
how those craft came to be in those situations... nothing more... obviously they 
ended up on land with pontoons...

as for "enjoy the bugs", that'll get one fired in many coding related jobs...

> There are so many more important things to
> handle here and I can't believe that this issue has been opened for almost half
> an year and that this discussion is still dragging so much...

the last post was Jul 15 until *you* brought it forward again...

> And on top of it all: I just tested this issue by selecting the floats on a
> concrete runway and with a reasonable weather the amount of movement is
> *minimal* (I had to compress time to 32x to observe anything). Now in a
> thunderstorm it can be seen without time compression, but honestly, if you leave
> a float plane in a concrete surface without tying it up in the middle of a
> bloody thunderstorm, then you'd get something exactly like that. So I'd say our
> "simulation" of a float on concrete surfaces is spot on.

the bug may very well have been fixed in the last four months... i have not 
attempted to go back through the issues and retest everything for various 
reasons... one being that it is easier for an issue to be revisited when someone 
finally has the time to take a look at it and i don't want to be pushy about 
things... i'm not a pushy person...

> With all that said, I am sorry to say but I am closing this issue.

no need to apologize if the issue is truly fixed... i won't hurt to leave it 
open if it isn't fixed, either...


PS: i hope you have a better day tomorrow than you apparently had in the last 
few days... your post was pretty harsh and you are/were obviously upset when you 
wrote it...

-EOT-

**Comment by gilbertohasnofb** [comment] 2015-11-05 23:27
@wkitty42 If you don't see where this is coming from, then there is nothing to be done. And I am sorry if you felt the tone was too harsh.
