### ISSUE TITLE
Full power makes tail tie-down raise

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#575] opened 2015-11-25 09:53 UTC
Full power makes tail tie-down raise. Either the aircraft shouldn't move at all or the tail tie-down should be made flexible somehow.

**Comment by wlbragg** [comment] 2015-11-29 02:55
I wanted to take another look at the hold -down code we tried to use for the tiedowns. Did we ever commit that to master or was it just a branch that never got merged? I looked for a while trying to find it but to no avail.

**Comment by onox** [comment] 2015-11-29 03:12
It ended up in a commit in a feature branch, but I think we later removed it again. But we can try the external force method, along with the dynamic tail tie-down that I mentioned lately. I can work on it after I have finished the JSBsim cabin heat+air stuff.

**Comment by wlbragg** [comment] 2015-11-29 04:09
:+1:

**Comment by onox** [comment] 2015-12-05 13:09
I started working on the dynamic tiedowns (which the technique I showed in https://github.com/Juanvvc/c172p-detailed/pull/573#issuecomment-159107814):

![fgfs-screen-386](https://cloud.githubusercontent.com/assets/3361585/11607831/ec00567a-9b56-11e5-9b68-6641e9d8aba4.png)
![fgfs-screen-387](https://cloud.githubusercontent.com/assets/3361585/11607832/ec043be6-9b56-11e5-8896-f9c3d4a0d58c.png)
![fgfs-screen-388](https://cloud.githubusercontent.com/assets/3361585/11607833/ec04aa7c-9b56-11e5-9e10-3536c15453e2.png)

As you can see the tiedown always points at the location to which it was set when the tiedown was enabled (made visible). Currently (not in the screenshots) the tail tiedown offset is always x=-5.5 and y=0.0, just like the static tail tiedown. This can be changed per bush kit of course.

The .ac file is just one object. I actually needed only three animations (yaw, pitch, scale). We could cut the object into two (beginning including that hanging thingy, and the rest of the rope) and then only scale the second. Also because of my superior (not) Blender skills, the tiedown is currently shiny red instead of dark red, so @wlbragg should take a look at it when I have pushed it to Github.

During testing I disabled the offsets in [`Models/c172p.xml`](https://github.com/Juanvvc/c172p-detailed/blob/master/Models/c172p.xml#L7-L10). @wlbragg Is there a particular reason for the very small z offset (-0.065)? Still need to check if these offset pose any problems.

One last comment: I haven't worked on the external force + PID controller yet, so the rope is currently flexible.

**Comment by gilbertohasnofb** [comment] 2015-12-05 14:03
Looks great, @onox! Can't wait to try them out :smile:

**Comment by legoboyvdlp** [comment] 2015-12-05 14:32
WHOA! Wonderful work :+1:

**Comment by wlbragg** [comment] 2015-12-05 16:57
>perhaps we could cut the object into two (beginning including that hanging thingy, and the rest of the rope) and then only scale the second.

Because scaling the "overhang" leaves the rotation of it in odd positions where it could potentially stick up (against gravity) VS down (with gravity)?

>Is there a particular reason for the very small z offset (-0.065)?

I imagine there was but I don't recall what it was.

**Comment by onox** [comment] 2015-12-06 06:23
> Because scaling the "overhang" leaves the rotation of it in odd positions where it could potentially stick up (against gravity) VS down (with gravity)?

I don't see how it can stick up. Normally the tiedown is horizontal (in the .ac file). Then I rotate it about the z-axis (heading). Then rotate about the y-axis (to point it at the ground instead of horizontal), then scale the whole thing so that it actually touches the ground.

It could only stick up if the pitch is > +90.0 degrees. But that won't happen; the pitch is always negative (between -90.0 and 0.0 degrees).

That scaling is also what causes the "overhang" to be scaled. That's what we can avoid if we split the object up into two pieces. But we first should see how much deformation there actually is (default length of the object is 2.6 meter).

**Comment by onox** [comment] 2015-12-06 22:56
I have pushed the dynamic tiedown code to [`bug-575`](https://github.com/Juanvvc/c172p-detailed/tree/bug-575).

@wlbragg Could you take a look at `Models/c172p-tiedowns.blend` (the file contains just one object) and try to fix the lighting issue of the tiedown-unit object? Export to `Models/Exterior/tiedowns/tiedown.ac`. Currently the object just doesn't care about the sun. I have seen this problem before when I had created some other object in Blender a while ago. Maybe my .ac exporter is a bit flaky.

![fgfs-screen-400](https://cloud.githubusercontent.com/assets/3361585/11616141/b4bfbfb0-9c74-11e5-80e3-13012a588319.png)

**Comment by wlbragg** [comment] 2015-12-07 00:59
Yep, I'll look at tonight.

**Comment by wlbragg** [comment] 2015-12-07 01:56
It was apparently just your exported .ac file. I didn't compare the two but I'd say your Blender export has problems.

I did take the opportunity to look at it close up and it seems to work well enough. The clip hardware is more rounded than oblong now (at least in some configurations) but actually look just as good. The hangover is fine, the strap is fine. The only thing I can make a comment about it the buckle, it is shortened. I don't know that it really matters though. Maybe @gilbertohasnofb has an opinion on it.

**Comment by wlbragg** [comment] 2015-12-07 02:35
One thing I noticed as far as the short buckle, if we started with a shorter strap overall, we could change the proportion of the buckle, overhand and end hardware.

**Comment by onox** [comment] 2015-12-07 06:22
> It was apparently just your exported .ac file

Okay, so it's not something in the XML that needs to be changed. I saw you did some specularity fix in a closed PR? That's unneeded?

**Comment by onox** [comment] 2015-12-07 06:23
What's a buckle? The metal thing at the ends?

**Comment by wlbragg** [comment] 2015-12-07 06:36
>I saw you did some specularity fix in a closed PR? That's unneeded?

Yes, that wasn't the problem. 

>What's a buckle? The metal thing at the ends?

No the black plastic looking thing that the strap overhang sticks out of.

**Comment by onox** [comment] 2015-12-07 06:42
Your new exported .ac file fixed the problem. It was the `emis 1.0000 1.0000 1.0000` of the `external_mat` material that was the problem. When changed to `emis 0.0000 0.0000 0.0000` the problem is fixed.

**Comment by gilbertohasnofb** [comment] 2015-12-07 07:58
> The only thing I can make a comment about it the buckle, it is shortened. I don't know that it really matters though. Maybe @gilbertohasnofb has an opinion on it.

Of course I have an opinion about it, I have opinions about anything and everything! :smiley: Personally, I don't think it's a big deal either, but if you want I can extend the buckle in the texture or we can UV-remap the object. But it looks fine to me.

**Comment by wlbragg** [comment] 2015-12-07 08:02
I'm fine with it also, lets just go with it and move on!

**Comment by gilbertohasnofb** [comment] 2015-12-07 08:04
:+1:

**Comment by onox** [comment] 2015-12-07 09:45
I'll add the external forces + PID's later this week.

**Closed** 2015-12-14 12:16 UTC
Labels: 3D model, animations (XML), bug
