### ISSUE TITLE
Tune g limits for wing damage

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#280] opened 2015-06-13 08:56 UTC
The current g limits might be too low and thus make it too easy to tear off the wings.

See https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-110781583 and https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-111212020 in #134.

**Comment by wlbragg** [comment] 2015-06-26 04:41
I agree, I was testing the new 180 engine and touched the water a tad bit hard, should have busted a pontoon way before both wings. We really need to tune what causes these damage conditions.

**Comment by dany93** [comment] 2015-06-27 10:15
I may have a fix for this, I have to do tests.

The broken wings on landing (particularly on water) comes from the breaking criteria, based on the g's. Correct IMO for flying (it is the POH criteria for every aircraft) but touching the water gives many g's *from the floats*, which wrongly break the wings despite not being held by the wings. An extra hint IMO for the excessive brutality of the hydrodynamics settings, but this is another issue.
My idea is replacing the g's with the *lift forces*, which come from the wings.
I look at this and propose something it if I feel it can work. Waiting for it, please do not change too much this part of physics.nas

**Comment by dany93** [comment] 2015-06-27 13:56
dany93 test branch: wing-force-damages https://github.com/dany93/c172p-detailed/tree/wing-force-damages

**Comment by onox** [comment] 2015-06-27 14:13
@dany93 Could you remove `max_positive` on line 18? It's unused now.

**Comment by onox** [comment] 2015-06-27 14:15
Also, can we increase the required g/force to something like https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-111212020?

**Comment by onox** [comment] 2015-06-27 14:16
`max_negative` isn't used either it seems :confused:

**Comment by onox** [comment] 2015-06-27 14:18
Same thing for lines 10 to 13.

**Comment by onox** [comment] 2015-06-27 14:51
@dany93 You can leave the current limits as they are if you want, I can no longer easily tear off my wings unless I go really fast (> 150 kt or something).

**Comment by onox** [comment] 2015-06-27 14:57
Btw, you can define the limits in `c172p-set.xml`.

**Comment by onox** [comment] 2015-06-27 15:04
@dany93 I've been doing some more testing. I noticed that in the air it's now very difficult to damage the wings at all. I need to dive towards the ground and then pull the yoke very fast. If I'm lucky I'll just get damage, but soon after that the wings get torn off.

**Comment by dany93** [comment] 2015-06-27 15:05
*(I received you previous message during my writing...)*

I can remove these useless lines with g, but I've left them on purpose in case wlbragg would like to use this criteria for something else. As you prefer (and @wlbragg).

For the different thresholds, my initial aim was to give a tool to enable wlbragg (or who wants to) doing what he wants with the thresholds and the effects.
For me, the thresholds are plausible, and the effects are an example of what can be done. But it is obviously pure feeling, choices, and I'm not better than you on this.
If you agree on the principle (force criteria on the wings), the best is that you change the values and the effects at your taste. I tried to do the FDM properties easy to understand and use, and the nasal file clear enough for that. Even the damages can take every value between 0 and 1, separately for each wing. This is like if you damage and had a yoke for the effect.

As you can see from the nasal file, there are three limits (equivalent to the previous ones with g's)
- 2550 lbs x 3.8 = 9690 lbs, (<==> 3.8 g's from the POH in normal category)
- 2550 x 3.8 x 1.25 = 12112 lbs,
- 2550 x 3.8 x 1.5 = 14535 lbs.

Tell me for the cleaning, and I let you do for the effects. The wing damage was a request from @wlbragg .

**Comment by dany93** [comment] 2015-06-27 15:10
>I need to dive towards the ground and then pull the yoke very fast

This is something we never do above a velocity which is given in the POH

**Comment by onox** [comment] 2015-06-27 15:11
@wlbragg I notice now that `<int n="15" alias="/fdm/jsbsim/wing-damage/left-wing"/>` and `<int n="16" alias="/fdm/jsbsim/wing-damage/right-wing"/>` should be floats.

To be honest though I'm not sure why they are floats. In principle each wing has 4 states:

1. Normal / repaired

2. Bended / damaged

3. Collapsed

4. Torn off

So we can use just two integers (one for each wing) for this to keep things simple. But in `<multiplay><generic>` we are using:

```xml
281         <int n="14" alias="/fdm/jsbsim/wing-both/broken"/>
282         <int n="15" alias="/fdm/jsbsim/wing-damage/left-wing"/>
283         <int n="16" alias="/fdm/jsbsim/wing-damage/right-wing"/>
```

Although I would like to refactor `<int n="1" alias="/sim/model/c172p/lighting/beacon-top/state"/>` and `<int n="2" alias="/sim/model/c172p/lighting/strobes/state"/>` to become floats (the voltage), because currently the transmission of the beacon and strobes is not very reliable.

**Comment by onox** [comment] 2015-06-27 15:15
@dany93 Ok, but it's just difficult to get bended wings. Maybe it's also because of the roll moment required.

**Comment by onox** [comment] 2015-06-27 15:15
I'll create a branch bug-280 and import your commit.

**Comment by onox** [comment] 2015-06-27 15:20
I see the following numbers for `wing-damage/left-wing` and `wing-damage/right-wing`: 0, 0.12, 0.3, 0.5, 1.0

**Comment by dany93** [comment] 2015-06-27 15:44
>I see the following numbers for wing-damage/left-wing and wing-damage/right-wing: 0, 0.12, 0.3, 0.5, 1.0

The used numbers are
- 0 : not damaged,
- 0.12: one wing damaged, can still fly by correcting with the ailerons.
 - 0.3: both wings damaged, can still fly with lift degraded. I have not set this value for one wing damaged because it necessitates ailerons + rudder correction to go on flying. Beyond the reach of many users.
- 1: one or both broken.

0.5 is not really used, `wing-damage/right-wing") < 0.5' is just to say "if this wing is only partly damaged, break it"

**Comment by onox** [comment] 2015-06-27 16:24
@dany93 I see they are used in the FDM. That's ok, but they don't really need to be transmitted over MP.

**Comment by onox** [comment] 2015-06-27 18:02
I have done some refactoring in branch bug-280, because there so many `getprop()` calls that it seems to cause lag when damage occurs.

**Comment by dany93** [comment] 2015-06-27 18:15
Does it mean that it is better to use nasal variables than `getprop()`?

**Comment by onox** [comment] 2015-06-27 18:26
I mean doing `getprop("A")` multiple times instead of doing it once and the storing it in a Nasal variable.

**Comment by dany93** [comment] 2015-06-27 18:40
That was I thought to have understood. When you say it, it seems logical, but I hadn't thought of this. It is not only for concision of the code...

**Comment by onox** [comment] 2015-06-27 18:48
I'm refactoring the MP properties a bit, to remove int[4], int[5], and int[14].

**Comment by onox** [comment] 2015-06-27 20:38
@wlbragg Could you take a look at [bug-280](https://github.com/Juanvvc/c172p-detailed/tree/bug-280)? I have managed to remove the three "broken" properties. Some remarks:

1. Currently we're using two floats to transmit the wing damage. Important values are:
    * 0: undamaged
    * 1: broken (torn off)
    * 0.12, 0.3: damaged
    As you can see the wing actually transmits three possible states, so an integer should be suffcient to use (0, 1, 2). That would mean we can often use `<equals>` instead of `<greater-than>` + `<less-than>`, which is what we need to use currently because they're floats.

    AFAIK the only reason why they are floats is because they're used in the FDM. But maybe we can make some small changes so `wing-damage/left-wing` and `wing-damage/right-wing` can be integers.

2. Same thing with the pontoons: we're using four properties, even though we only need two.

3. I find it too easy to tear off the wings. I find it very difficult to just get one or two wings damaged.

4. I find it almost impossible to get the "collapsed" state.

5. For the "collapsed" state we use `/fdm/jsbsim/crash`. But AFAIK that property is used by the MP lag code (in FlightGear/fgdata itself) to transmitting the position. It's also used by old c172p models, so I think we should use a different index (not int[3]) + not use `/fdm/jsbsim/crash`, but give it a proper name. Something like `/fdm/jsbsim/wing-damage/collapsed`.

**Comment by wlbragg** [comment] 2015-06-27 20:40
>In principle each wing has 4 states:

Not quite
You need to be careful refactoring these.
In reality we have:

normal / repaired
both damaged
both broke
left damaged / right not
left broke /right not
left damaged / right broke
right damaged /left not
right broke / left not
right damaged left broke

contact unit[4] and unit[5] control L and R wing broken individually.
props control the rest.

I'll be able to respond in more detail tonight if you have more questions.

**Comment by onox** [comment] 2015-06-27 20:41
Ok, 10 states:

normal/damaged/broken for left wing x normal/damaged/broken for right wing = 9

Plus both wings collaped = 10 :smile:

**Comment by wlbragg** [comment] 2015-06-27 20:52
Yeah. forgot that one! :smile:

**Comment by onox** [comment] 2015-06-27 20:54
Anyway, what I'm trying to say is that these three "broken" properties are not needed. We can do without them.

**Comment by wlbragg** [comment] 2015-06-27 21:01
Yeah, by using an int or a float that can represent multiple states.
I was originally going to do that but dany93 needed a different configuration and I told him to do what he needed, it left us with extra props we really didn't need. I think it was a communication gap between the two of us. My fault for not clearing it up back then. So have at it!

**Comment by onox** [comment] 2015-06-27 21:02
What do you think about (3) in https://github.com/Juanvvc/c172p-detailed/issues/280#issuecomment-116137167?

**Comment by wlbragg** [comment] 2015-06-27 21:10
I agree, it seems easier to tear it off than damage it.

**Comment by onox** [comment] 2015-06-27 21:12
Btw, about the wing-damage properties. What about:

0 = undamaged/unbroken
1 = broken
2 = 0.12
3 = 0.3

Then we can just do a wing-damage/left-wing > 1 check in the model xml file.

**Comment by onox** [comment] 2015-06-27 21:18
I'm using a `<switch>` in the FDM, so that was fairly easy.

**Comment by onox** [comment] 2015-06-27 21:47
I've made the changes to make the two properties ints. Pushing in a minute.

**Comment by onox** [comment] 2015-06-27 22:39
I think I have fixed #336

**Comment by dany93** [comment] 2015-06-28 12:46
>Btw, about the wing-damage properties. What about:

>0 = undamaged/unbroken
1 = broken
2 = 0.12
3 = 0.3

Previously, the wing damages in flight could be fully controlled by only two properties. Directly understandable, intuitive and easy to use. But they are  0 - 1, double format.
You have changed it for four states (integers), and a switch to do the connection to the FDM.
Which worries me is for the future contributors.

Wouldn't have been more easy and more clear to keep the same properties but to have:

0 = undamaged/unbroken
100 = broken
12 = 12% damaged
30 = 30% damaged

They are integers, 
And we would have divided the factor in the FDM by 100, value = +/- 0.003 instead of +/- 0.3
```
            <function name="aero/coefficient/Cllwdmg">
                <description>Roll_moment_due_to_damaged_left_wing</description>
                <product>
                    <property>aero/qbar-psf</property>
                    <property>metrics/Sw-sqft</property>
                    <property>metrics/bw-ft</property>
                    <property>>wing-damage/left-wing</property>
                    <value>-0.003</value>
                </product>
            </function>
            <function name="aero/coefficient/Clrwdmg">
                <description>Roll_moment_due_to_damaged_right_wing</description>
                <product>
                    <property>aero/qbar-psf</property>
                    <property>metrics/Sw-sqft</property>
                    <property>metrics/bw-ft</property>
                    <property>wing-damage/right-wing</property>
                    <value>0.003</value>
```
This avoids the intermediate function with the switch in the FDM, which hampers the understanding.

May be too late, or not easily consistent with you code for other damages?

Question: I didn't know for this way of using a switch. Where did you find it, is it explained somewhere? There is a severe lack on this.

**Comment by dany93** [comment] 2015-06-28 13:37
A weird detail:
When I am in the `bug-280` branch, the pilot **appears** when the option `Human models` is **unchecked**, and I have to check it to not have it.

**Comment by onox** [comment] 2015-06-28 13:57
> They are integers,
And we would have divided the factor in the FDM by 100, value = +/- 0.003 instead of +/- 0.3

Please read the commits in the branch. See this: https://github.com/Juanvvc/c172p-detailed/blob/9493801c92f2cbc15f29b283b2632288f2292e41/c172p.xml#L908-L926

**Comment by onox** [comment] 2015-06-28 14:02
Ah, sorry, I should better read, you actually found the switch. The reason I didn't use:

0 = undamaged/unbroken
100 = broken
12 = 12% damaged
30 = 30% damaged

is because otherwise I would have to add lots of extra checks in `Models/c172p.xml` to make sure that 100 is not considered when I want to check that the wing is just damaged.

**Comment by onox** [comment] 2015-06-28 14:06
> When I am in the bug-280 branch, the pilot appears when the option Human models is unchecked, and I have to check it to not have it.

Thanks for finding this. I'll take a look at it. It did change some code related to it, so I'm not surprised.

**Comment by onox** [comment] 2015-06-28 14:15
Fixed it.

**Comment by onox** [comment] 2015-06-28 14:18
@dany93 About the float/int problem: I was thinking about it and it's only the model that needs to know whether the wing is normal/damaged/broken. So what we could do is:

1. Just use floats in the FDM. Remove the two switches

2. Use floats in `Nasal/physical.nas`.

3. Write two small funtions/filters that output 0 to a new property if normal, 1 if broken, 2 if damaged (no matter how much). That would mean very little changes to the model file, so it's easy to do.

**Comment by dany93** [comment] 2015-06-28 15:19
If I understand well:
- items 1. and 2. would amount to restore the previous form in `Nasal/physics.nas` and the FDM,
- your filter (item 3.) would do the interface between `physics.nas` and the `Models/`. I guess that the new property = 2 value ("damaged") can be flexible enough (like `new property = 2` for damage` = 0.1 to 0.9`, or `not 1 and not 0`) in case someone would change the damage value (currently 0.12 or 0.3).

Good idea, I like it.
But it depends on you, if you accept my remark, enough to do this extra work.

1 or 2 for damaged or broken is rather for the Models/ management side, @wlbragg  and you.  I'm not disturbed by 2 for damaged, because I'm used to 1 for broken. Purely mnemonics.

Anyway, thank you.
And thank you too for your JSBSim link. I had it, but there so much in it and so concise that finding a subject is not always easy. Moreover, I must admit that I had forgotten it....
And your switch will have driven me to learn this form.

**Comment by onox** [comment] 2015-06-28 18:33
Alright, I'll make the necessary changes then :smile:

**Comment by onox** [comment] 2015-06-28 19:46
@dany93 I have made the necessary changes.

**Comment by dany93** [comment] 2015-06-28 20:38
Thank you onox.

**Comment by onox** [comment] 2015-06-28 20:48
I have made some changes to the lift forces needed to damage/break a wing. Pushing in a minute.

**Comment by dany93** [comment] 2015-06-28 20:55
Sorry, but I have to leave. This will be for to morrow (for me).

**Comment by onox** [comment] 2015-06-28 20:58
Now I'm noticing that JSBSim doesn't execute my two `<switch>` blocks in replay mode :confused:

**Comment by onox** [comment] 2015-06-28 21:51
Fixed it by moving it to a `<property-rule>`.

**Comment by onox** [comment] 2015-06-28 23:35
@wlbragg I have adjusted the max lift force. Could you test it a bit?

**Comment by onox** [comment] 2015-06-30 16:30
@wlbragg Could you explain why the overspeed/over-g code in `Nasal/physics.nas` often checks for damage on the opposite wing when it wants to damage/break the other wing?

For example, see [this](https://github.com/Juanvvc/c172p-detailed/blob/master/Nasal/physics.nas#L411-L415). The code checks that the left wing is undamaged, and if it is, it damages the right wing. Is this really how it should be or is this a mistake?

**Comment by dany93** [comment] 2015-06-30 17:33
No, this is not a mistake.
I have written this code several weeks ago and I don't remember well the details.
The idea is, you have 4 states:
- one wing damaged (0.12) ==> the aircraft can still fly by aileron correction,
- two wings damaged (2 x 0.3) ==> can still fly, lift degraded,
- one wing broken ==> rapid roll spin,
- two wing broken.

Without these checks for the other wing, you hardly had some of these states because your attempts to correct or the movements provoked a second partial damage and you never had some of them, like one wing damaged or one wing broken.
Try by deleting this and you will see what I mean. In RL, a second partial damage is possible, but in FG all of this is scenarios....

**Comment by onox** [comment] 2015-06-30 17:56
Okay, I have left the checks as they are when I moved the code to [`Systems/c172p-damage.xml`](https://github.com/Juanvvc/c172p-detailed/blob/bug-280/Systems/c172p-damage.xml).

**Comment by wlbragg** [comment] 2015-07-01 03:23
Sorry RL has gotten in my way and I am really slow to catch up and respond.
dany93 may be correct, also in the case of checking if one wing is damaged prior to damaging the other wing sometimes was to account for both wings damaged. If one is already damaged them we go to both wings damaged condition and not just one.
Like dany93 said, it's been awhile since we worked on this part of the logic, but I agree, it was by design.

**Comment by dany93** [comment] 2015-07-01 16:33
@onox
I see that you have completely transferred the damage code from nasal to xml. Important improvement, very good operation. I'm impressed.

I have made tests. Done at max weight (2550 lbs for 180 hp).

## 1. Gear damages

**Moderately hard landing** (stalled from some height) or with the nose slightly too low:
Correct. The nose gear alone or the main gear break, or both, or the three, with the expected logic. The nose gear may be a bit hard to break, but not by much.

**Crosswind landing** (15 kts crosswind):
A bit touchy, not excessively. I'd say: good. With a correct decrabbing and upwind yoke, of course.
Without decrabbing, one of the main gears break (as expected), sometimes the nose gear too if the landing is a bit hard.

So, the gears globally behave well with good landings, and break with moderately "bad" maneuvers. Very better than most FG aircraft, even if it may still be refined.

I had 2 or 3 (rare) cases where the nose gear broke unexpectedly (moderately braking during a turn, which maybe is not to do, or by releasing the brakes at start).
***I wonder if the 1500 lbs threshold is not a bit low*** (even with the 0.3 compression criteria, which is useless in the case above). Normally it should be just enough, the nose force reaches about 1400 lbs at strong braking, but 1500 lbs is not such a large margin.
A possibility would be 2400 lbs threshold with no compression criteria. I have made some tests yesterday which seem OK with that. More tests would still be needed if we want to take it.


## 2. In-flight wing damages

### - over-g (overload) ###

Difficult to test systematically because everything goes very fast.
However, I have seen almost all the damage configurations (left wing 0.12, right wing 0.12, both wings 0.3, one wing broken).
***I could not reach "both wings broken" by the higher*** `limits-lift-high`.

***I think that the thresholds are too high.***
Moreover, if we look at the maneuvering speeds 552S POH pdf page 48/384 http://www.engineersflyingclub.org/planes/552SPPOH.pdf
![maneuvering-speed2015-06-27 17 13 01](https://cloud.githubusercontent.com/assets/11994061/8459340/ca4c0804-201c-11e5-8f2d-32f674c8fb5f.png)

 these speeds (in KCAS - KIAS) correspond to about 3 - 3.5 g's at 1900 or 2550 lbs for an abrupt pulling of the yoke. Above these speeds (even before reaching the yellow arc of the tachometer), a damage is likely to occur.

### - Over speed

Everything OK.

**Comment by wlbragg** [comment] 2015-07-01 20:05
>@onox
I see that you have completely transferred the damage code from nasal to xml. Important improvement, very good operation. I'm impressed.

Yes, big improvement, I should have taken the time to learn and do from the beginning, but nasal was more in line with my current skill set at the time. I'm happy to see this change over. It really is look good and performs better.

**Comment by onox** [comment] 2015-07-01 20:18
@dany93 Those thresholds are indeed too high. `limits-lift-high` is about 16000, which is way too high :smile:

I got about 6500 lbs at 88 KCAS (1900 lbs), to 8000 lbs at 102 KCAS. So that's about 3 - 3.5 g you're talking about.

How would you like to see the `<pure_gain>`'s altered? I think `/limits/max-lift-force` needs to be lowered, and the gains for medium (1.4) and high (1.75) as well.

**Comment by onox** [comment] 2015-07-01 20:21
@wlbragg What do you prefer for the nose gear? 1500 lbs + 0.3 compression-ft or 2000 lbs + no compression-ft check? Note that if idle on the ground, a compression of about maybe 0.1 to 0.2 is easily reached. 0.0 only in the air. So I added the compression-ft check just so that it looks a bit better in replay mode.

**Comment by onox** [comment] 2015-07-01 20:23
We could keep `damage/limits-lift-high` fairly high, so that it only triggers if you smash your plane on the ground.

**Comment by dany93** [comment] 2015-07-01 21:45
@onox 
It does not work like that.
As indicated by its name, this force is a **lift** force (from the air on the wings). I have changed the breaking criteria from *g's* to *lift force* `forces/fbz-aero-lbs` precisely in order to avoid a break of the wings by bouncing on water (and on the ground for the same reason). From now, the wings are broken by the lift force only.
When you hit the ground or the water, the breaking or smashing cause for the wings is their inertia. Here, you must use the g's.

**Comment by onox** [comment] 2015-07-01 21:49
Ok.

**Comment by wlbragg** [comment] 2015-07-01 22:27
>@wlbragg What do you prefer for the nose gear? 1500 lbs + 0.3 compression-ft or 2000 lbs + no compression-ft check?

The 1500 lbs + 0.3 appears to be good, the 2000 without compression-ft check broke to easy, if indeed I had my test conditions all set correctly.

**Comment by dany93** [comment] 2015-07-01 22:44
>Those thresholds are indeed too high.
How would you like to see the <pure_gain>'s altered? I think /limits/max-lift-force needs to be lowered, and the gains for medium (1.4) and high (1.75) as well.

The only objective number I have is from the POH, http://www.engineersflyingclub.org/planes/552SPPOH.pdf pdf page 54/384
![load-factors-2015-07-02](https://cloud.githubusercontent.com/assets/11994061/8465946/2868c360-204e-11e5-94d4-58977078865c.png)
I take Normal Category, which gives, translated in lift force at max weight, 2550 x 3.8 = 9690 lbs. There are good reasons to take this as a base.
Starting from this and from the > 150%, I had initially *chosen* "both wing broken" for 3.8 x 1.5 = 5.7 g's.
And 3.8 x 1.25 = 4.75 g's for the intermediate possibility of one wing broken
But this was a choice, a personal evaluation.
That was initially for 2400 lbs, now I take 2550 lbs (not important taking into account our lack of accuracy to choose our limits). Which makes
3.8 x 2550 = 9690 lbs as the first base threshold 
3.8 x 1.5 x 2550 = 14535 lbs for both broken (150 %),
3.8 x 1.25 x 2550 = 12113 lbs for any intermediate damage.
In terms of <pure_gain>'s, it comes to 1.5 and 1.25.
1.5 has some justification according to the POH.
You have changed them for 1.75 and  1.4.
You have the numbers and why my choices....

**Comment by onox** [comment] 2015-07-02 00:13
> In terms of 's, it comes to 1.5 and 1.25.
1.5 has some justification according to the POH.
You have changed them for 1.75 and 1.4.
You have the numbers and the reasons for my choices....

I'll change it back to 1.5 and 1.25. I'll also see if I can add a check for the negative load (-3420 lbs) and take flaps into account as well.

**Comment by onox** [comment] 2015-07-02 01:09
@wlbragg Can you take a look at the test conditions for damaged pontoons? (At the bottom of `Systems/c172p-damage.xml`) Currently the `compression-ft` for contact units (13, 15, 17, and 14, 16, 18) is 0.75, but I think that is maybe too high :confused:

**Comment by wlbragg** [comment] 2015-07-02 04:17
Not high enough, I had damage taxing over apron.
Maybe it has always done that. 

I'm still testing.

**Comment by wlbragg** [comment] 2015-07-02 04:21
Yeah it broke just rolling out on the runway during takeoff. Also this branch lost the pontoons upon both broken or both damaged. Surely this is fixed in master?

**Comment by wlbragg** [comment] 2015-07-02 04:46
I landed on water and back at the airport without breaking the pontoons, so I don't really know why it broke so easy on take off.

**Comment by onox** [comment] 2015-07-02 05:23
@wlbragg Which commit did you use for testing?

**Comment by onox** [comment] 2015-07-02 05:27
> Not high enough, I had damage taxing over apron.

Damage or broken pontoon?

> Also this branch lost the pontoons upon both broken or both damaged.

Pontoon damage is done individually, so you can have "both damaged" or "both broken".

> I landed on water and back at the airport without breaking the pontoons

If you look at [this](https://github.com/Juanvvc/c172p-detailed/blob/bug-280/Systems/c172p-damage.xml#L461-L468), you see it uses `contact/unit[i]/compression-ft GT 0.95`, but `compression-ft` is apparently always 0 on water?

**Comment by onox** [comment] 2015-07-02 05:28
Do you want to be able to break a pontoon on the water? Or just only on land?

**Comment by onox** [comment] 2015-07-02 05:38
I'm not able to damage the pontoons really. I find 0.75 too high. If I smash the plane into the ground I can break (but not damage) the pontoons though.

**Comment by onox** [comment] 2015-07-02 05:44
I have moved the wing collapse logic to XML as well, which was the final piece. So it's just the pontoon damage conditions that need to be tuned. See [line 433 to 435](https://github.com/Juanvvc/c172p-detailed/blob/bug-280/Systems/c172p-damage.xml#L433-L435) and [line 475 to 477](https://github.com/Juanvvc/c172p-detailed/blob/bug-280/Systems/c172p-damage.xml#L475-L477).

**Comment by wlbragg** [comment] 2015-07-02 16:06
I used branch bug #280, same as I used to test the nose gear logic. I don't see a "Fix <test> blocks for damaged pontoons"
The bug #280 branch also still had both shadow choices in the gui.

>Damaged or broken pontoon?

"Damage" on the apron.

>Pontoon damage is done individually, so you can have "both damaged" or "both broken".

I'm not sure what your saying here. I was saying that using this branch caused both pontoons to disappear, "vanish", as in bug, when I think it was "broke both" condition, however it was achieved. So I am concerned if this is just an old branch and that bug has been corrected, I tested the wrong branch or it is still a bug that needs to be fixed.

>if a pontoon breaks, it's z-position's aren't updated.

It really never required it for the pontoons.

**Comment by wlbragg** [comment] 2015-07-02 16:38
I'm testing pontoon in  master right now and it is not working correctly. I can only get "broken" and that by slamming into the ground really hard. What should be causing damage does nothing except I am getting sparks on touchdown, "even soft". Unless it is because I am in a some kind of BUG state because I am just hitting "Position aircraft in air".

Time passes....

That is exactly what it is. Hitting "Position aircraft in air" is causing pontoon gear to not function anymore, as in the retract and extend do not reposition the aircraft "contact points".

It's kind of difficult to test when you are fighting against the sim itself.

**Comment by wlbragg** [comment] 2015-07-02 17:02
This #280 branch is really old, why are we using it to test the new damage model?

I just verified that "both pontoons broken" is the version that they disappeared in, BUG.

Also still has the popup saying that you broke them, didn't we get rid of that too, a long time ago?

@onox, I don't know what happened here but don't you want to add the new xml damage model to a clone of master and test that instead?

**Comment by onox** [comment] 2015-07-02 18:30
> The bug #280 branch also still had both shadow choices in the gui.

Because this is bug-280, not master. If you really want I can merge master to bug-280, but it's not necessary. The only think you're missing currently is the stuff from bug-148, bug-145, bug-349, bug-355, bug-356, which are all small fixes and not related to the stuff that is fixed by bug-280.

**Comment by onox** [comment] 2015-07-02 18:32
> I'm testing pontoon in master right now and it is not working correctly.

In that case pontoon damage is not working in master _and_ not working in bug-280.

**Comment by onox** [comment] 2015-07-02 18:35
>> if a pontoon breaks, it's z-position's aren't updated.

> It really never required it for the pontoons.

But if the z-positions aren't updated, then the aircraft won't fall onto one of its sides when one pontoon is normal while the other is broken.

**Comment by onox** [comment] 2015-07-02 18:37
> I don't know what happened here but don't you want to add the new xml damage model to a clone of master and test that instead?

bug-280 is a fork of master. Both master and bug-280 branch have the commit "Merge pull request #342 from Juanvvc/bug-273" from 2015-06-26 22:26.

**Comment by onox** [comment] 2015-07-02 18:40
These should be the two top commits in bug-280 on your computer:

```
511df90 Move wings collapse damage logic to JSBSim system
5c6ffb3 Fix <test> blocks for damaged pontoons
```

**Comment by onox** [comment] 2015-07-02 18:45
@wlbragg Let me ask you this then: which situations do you want to have and which do you not want to have:

1. "left pontoon damaged and right pontoon normal"
2. "left pontoon broken and right pontoon normal"
3. "left pontoon normal and right pontoon damaged"
4. "left pontoon normal and right pontoon broken"
5. "both pontoons damaged"
6. "both pontoons broken"

**Comment by wlbragg** [comment] 2015-07-02 22:08
And left damaged right broken and vice versa

**Comment by wlbragg** [comment] 2015-07-02 22:34
There is never a case when no pontoons are showing, damaged and broken both have pontoons showing. Also, ever since the hydro FDM was installed, there was no need to have movable contact 
points.

My point is we are testing using a branch that has a no pontoon condition, meaning it is broken, buggy. How are we supposed to know if things are working right when we are using a buggy branch. It doesn't mean anything to me what comits are in it as long as any of the damage logic is buggy, which it is.

**Comment by wlbragg** [comment] 2015-07-02 22:45
I have the right branch and those two comitts.

I don't remember what comit fixed the "no pontoon" conditon.

**Comment by onox** [comment] 2015-07-02 23:34
Okay, so the only problem is that the a pontoon disappears when that particular pontoon is broken?

> It doesn't mean anything to me what comits are in it as long as any of the damage logic is buggy, which it is.

Could you please be more specific? :confused:  I hope you're referring to just the pontoons? (not the gear and the wings, those are okay now, right?)

**Comment by onox** [comment] 2015-07-02 23:42
I have a bit difficulty trying to understand what you're saying, but I think you mean that (currently) "broken" means that the pontoon is invisible. This is what I see in master. In bug-280 the whole pontoon just disappears when it is broken. I'll investigate and fix it.

![fgfs-screen-189](https://cloud.githubusercontent.com/assets/3361585/8490139/7faf967c-2124-11e5-899c-3579ab7cd87e.png)

**Comment by onox** [comment] 2015-07-03 00:00
Fixed in bug-280 branch

![fgfs-screen-190](https://cloud.githubusercontent.com/assets/3361585/8490339/3cedb5c8-2127-11e5-9d59-03888821153a.png)

**Comment by wlbragg** [comment] 2015-07-03 00:00
Sorry I'm on a tablet with a bad connection. Yes the bug in 280 is the pontoons disappear, in master they never disappear which is the correct behavior.

**Comment by onox** [comment] 2015-07-03 00:01
Pull @wlbragg, I have just fixed it already :smile:

**Comment by wlbragg** [comment] 2015-07-03 03:58
@onox. OK I pulled 280 and merged master so I got rid of all the other issues. Did a couple quick tests.

Verified the "both broken" now show correctly. 

I was able to break both, break one and damage the other, damage one.

Seemed maybe a little stiff (hard to damage). I would think "damaging" a pontoon would be really easy beings they are probably aluminum (especially without gears). With gears, maybe a little harder to "damage". Breaking however should be difficult, IMO. 
This is just an opinion based only on my limited knowledge of metals and common sense.

But all in all it wasn't to out of what I might expect in RL.

I think some of the problem with getting consistency with the pontoons is that the 3 x 2 contact points being on the bottom of the pontoons do not register a nose dive (45-90 deg) into the ground. I really think we may need to add two contact points that are at the front, lower, tip of the pontoons and add those to the damage equation.

Any thoughts on that?

**Comment by onox** [comment] 2015-07-03 13:18
> Seemed maybe a little stiff (hard to damage).

I was already trying to say that it's hard to damage because the constants are 0.75 (for damaged), which is close to 0.95 (for broken). Have you tried setting them to 0.35 for example?

> I really think we may need to add two contact points that are at the front,

Don't we already have the two front gear for that?

**Comment by dany93** [comment] 2015-07-03 13:51
Sorry for coming again to the wing damage...

I am a bit worried about the over-g behavior for wings damaged.
To remind, the lift force criteria instead of initial g's was implemented to avoid unexpected wing breaking on hitting the ground or water.
But the limit currently used (that I proposed in a first time) was based on the maximum Gross Weight possible, 2550 lb lift-force (180hp engine). This makes the `damage/limits-lift-high` unreachable for both wings broken by over-load / over-g.

By changing the weight reference from *maximum weight* (2550 lb) to *current weight* for calculating the limits, the limits become reachable again. Moreover, the limits come again to being in g's units (3.8 g, 1.25 x 3.8 g, 1.5 x 3 .8 g), although the damage criteria is still the lift force. It is more in accordance with the [POH ] (https://github.com/Juanvvc/c172p-detailed/issues/280#issuecomment-117843756) which specifies the limits in g's.

https://github.com/dany93/c172p-detailed/tree/bug-280

My tests (done at default load 2074 lbs with 180 hp):
By pulling abruptly the yoke in straight line
- < 100 - 110 KIAS: no damage
- 120 KIAS: both wings damaged (2 x 0.3)
- 140 KIAS: both wing broken.

The velocity when first damage occurs is not far (just a bit higher) than the [POH maneuvering speeds] (https://github.com/Juanvvc/c172p-detailed/issues/280#issuecomment-117740228).

For obvious reasons, the high g limit is not more reachable than previously at maximum weight.

Needless to say that I greatly prefer this formulation.

**Comment by onox** [comment] 2015-07-03 14:08
I think that's better too, I was already wondering that we didn't make use of the current weight.

**Comment by onox** [comment] 2015-07-03 14:10
Now we're talking about the wing damage again, we should still add conditions for the negative g's (-1.52) .

**Comment by dany93** [comment] 2015-07-03 14:30
As you want.  I hadn't put it in the first step. But is it worth to make the code longer, the negative g's are much less likely to be practised?
And I wonder what it will do when we go to spinning because of the other damages. The risk is breaking everything each time...

**Comment by onox** [comment] 2015-07-03 14:32
I'm using something like this:

```xml
<switch name="over-g-medium">
    <output>damage/over-g-medium</output>
    <default value="0"/>

    <test logic="OR" value="1">
        damage/force-aero-lbs GT damage/limits-lift-pos-medium
        damage/force-aero-lbs LT damage/limits-lift-neg-medium
    </test>
</switch>
```

**Comment by onox** [comment] 2015-07-03 14:37
I think I'm going to remove the negative g's again. I find it very hard to trigger them.

**Comment by onox** [comment] 2015-07-03 14:41
@dany93 I have decided to not do anything with the negative g's. Can you give a :+1: at PR #365 if you're ok with everything?

**Comment by dany93** [comment] 2015-07-03 14:42
Poor pilot. Everything goes wrong. The engine has already stopped....

**Comment by onox** [comment] 2015-07-03 14:43
?

**Comment by dany93** [comment] 2015-07-03 14:44
Yes for the PR, but how?

**Comment by onox** [comment] 2015-07-03 14:45
What do you mean "how"? :open_mouth:

**Comment by dany93** [comment] 2015-07-03 14:47
I have never made PR's other than to master.
Is it a PR to upstream: bug-280 branch?

**Comment by onox** [comment] 2015-07-03 14:48
No no, you don't have to do a PR. I have already imported your commit into our bug-280 branch.

**Comment by onox** [comment] 2015-07-03 14:48
Look at https://github.com/Juanvvc/c172p-detailed/pull/365/commits :smile:

**Comment by dany93** [comment] 2015-07-03 14:56
There so many commits... Do you expect me to test?
If it is the bug-280-branch that I have pulled this morning, I have seen nothing wrong, but I am far from having used everything.
I see my last commit, the lines of which were cleaned if I remember well.

**Comment by onox** [comment] 2015-07-03 15:00
The only difference between dany93:bug-280 and Juanvvc:bug-280 is that the latter is one commit ahead of yours (to fix those "Failed to tie property fcs/" warnings), so if you're okay with dany93:bug-280, then you can also be ok with the branch in PR #365.

**Comment by dany93** [comment] 2015-07-03 15:07
OK. Sorry.

**Comment by wlbragg** [comment] 2015-07-03 17:25
>Don't we already have the two front gear for that?

Yes, but they are bogey and don't appear to react to front and side forces?

When crashing at 30+ degree, it is almost impossible to do damage, you just bounce a little.

**Comment by wlbragg** [comment] 2015-07-03 17:48
The front bogies are catching it up to almost 90 with enough force. It probably could be softened slightly, but I would rather have it too hard than to soft.

**Closed** 2015-07-03 17:48 UTC
Labels: enhancement
