### ISSUE TITLE
Strange shadow object

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#302] opened 2015-06-15 17:40 UTC
Just notices a strange line that moves with the shadows. For these images, I am using the float variant:

http://s29.postimg.org/960v77xdj/fgfs_screen_001.png
http://s29.postimg.org/ajsi2iwmv/fgfs_screen_002.png

**Comment by wkitty42** [comment] 2015-06-15 18:10
confirmed! hahaha... i had to get in *just* the right orientation to see it but yes, i see it... ya gotta have the sun behind ya so you can see the shadow of the tail assembly on the panel like that... it took me a bit to find it...

it kinda looks like maybe a scratch on the rear window but when i went to heli view to try to see if there was a scratch there, i thought i also saw that line on the door post at the front of the rear window... i'm not sure what livery you were flying but don't some of them have ""wear"" markings? could it be a scratch on the window? i may have gotten lucky and chosen the same livery... i'll try to test again now that my craft crashed due to an AP "foul up" on my part :laughing:

**Comment by gilbertohasnofb** [comment] 2015-06-15 18:13
Thanks for testing this! This must be something on the cubemap created by @wlbragg since it moves with the shadows -- or at least that's what I think :smile:

**Comment by wkitty42** [comment] 2015-06-15 18:26
@gilbertohasnofb yeah, that's kinda what i'm thinking, too... i was able to do it again quite easily... it is exactly the same for all liveries...

Advanced Weather ON
Time set to AFTERNOON
KMCO runway 18R
heading bug set to 180
take off at full power
turn on AP and click the HDG button to hold 180
set heading bug to 117
set AP to climb at 200 or 300 fpm

that line should be over there on the right panel side... i've held it in the far right instrument circular cutout place for the entire time i've been typing this... check out these two shots :wink: 

inside the cabin...
![fgfs-screen-056](https://cloud.githubusercontent.com/assets/4641713/8167147/4ca1f508-136a-11e5-9d8e-fe07e424d714.png)

from heli view...
![fgfs-screen-055](https://cloud.githubusercontent.com/assets/4641713/8167168/7ad05c1c-136a-11e5-80af-c11cbe49bc40.png)

**Comment by onox** [comment] 2015-06-15 19:56
I think @wlbragg did something to the instruments to prepare them for the ALS flashlight. I noticed it too.

**Comment by wkitty42** [comment] 2015-06-16 01:29
i dunno... either way, it was easy enough to find once i knew to look with the tail assembly behind me... the rather shocking thing was that it was also visible from outside the craft as my second photo shows...

my initial thought was, i think i stated, a scratch in the rear window or the right rear side window... TBH, though, i wouldn't worry about it at all.. it adds to the mystique of the craft... leave it alone, ya know? :angel:

**Comment by gilbertohasnofb** [comment] 2015-06-16 01:31
> TBH, though, i wouldn't worry about it at all.. it adds to the mystique of the craft... leave it alone, ya know?

Oh, it bothers me quite a lot. I am quite compulsive about things out of place, and once I realize something isn't right then I will see it all the time. Right now I think I watch this line more than I watch my airspeed :wink:

**Comment by wkitty42** [comment] 2015-06-16 01:41
@gilbertohasnofb hey, don't think you are the only one with OCD problems :wink: :laughing: they are one of my major problems to deal with... the recent commit of the ancient history really set me off and it still does when i go back through the git log history... especially since the mess is out of proper sync... it is al i can do to stay quiet about it... i said my piece (and got a reprimand!) on the forums about it but still...

do you count steps and/or actions in threes as i do?

**Comment by wlbragg** [comment] 2015-06-16 02:21
I found it, it is on the cube map. It is a little bit of edge that isn't cleaned up. Funny though because it has been there this whole  time.

**Comment by wlbragg** [comment] 2015-06-16 02:32
I pushed the fix for it. It is part of the PR Refactor wing damage and broken over MP #305.

**Comment by wkitty42** [comment] 2015-06-16 03:55
let's wait until after the merge so we can play big hunter and see if we can find it again :laughing:

**Comment by gilbertohasnofb** [comment] 2015-06-16 10:46
@wlbragg thanks for the PR. I can't check it right now so I won't merge it, but if it's still open tonight I will have a look on it.

@wkitty42 
> hey, don't think you are the only one with OCD problems

Yeah, particularly here on GitHub. I think at least half of people here are obsessive compulsive neurotic guys with Asperger :wink:

**Comment by wlbragg** [comment] 2015-06-18 02:32
This should be fixed so I am closing it.

**Closed by wlbragg** 2015-06-18 02:32 UTC
Labels: bug, effects
