### ISSUE TITLE
Parking Brake not set at startup

### ISSUE THREAD

**Issue by debdog** [Juanvvc/c172p-detailed#454] opened 2015-10-01 17:08 UTC
This can be devastating on some runways/parking positions.

FG 3.6 RC

**Comment by gilbertohasnofb** [comment] 2015-10-01 17:12
I thought that the parking brake status was persistent among FG sessions, but I can't test it right now. Could you please try to quit FG with the parking brakes on and check if they are still on next time you load it?

**Comment by debdog** [comment] 2015-10-01 21:06
Hi Gilberto, indeed they're set at startup if I quit FG with the brakes on. If FG does that by itself this definitely is a bug. For some settings autosave just is not a good idea. I'll test some other planes on their behaviour regarding the parking brakes. I know the ju52 always starts with brakes enabled, though.

**Comment by Juanvvc** [comment] 2015-10-01 21:19
It is not a bug, it is a feature: the parking break state is saved between sessions, and you'll find this behaviour only in the c172p because we code this explicitly.

I reckon it is something unusual: it makes sense if you always park and spawn the aircraft in the same hangar. But if you can quit the simulator in the middle of the flight, the c172p will show a completely wrong state next time you start FlightGear.

The bugs we discussed a couple of weeks ago in #121 #439 and some others are related to this issue: we are saving the state of the aircraft, but the tutorial subsystem is making some assumptions about the initial state of a generic aircraft. As a consequence, we need this little hack of resetting the aircraft in the first step of the tutorial and not in the preset section.

I believe we need a "reset" command to cope with this situations, and a new option for the aircraft: save the previous state or reset the aircraft each time you start the simulator.

**Comment by gilbertohasnofb** [comment] 2015-10-01 21:29
> I believe we need a "reset" command to cope with this situations, and a new option for the aircraft: save the previous state or reset the aircraft each time you start the simulator.

Completely agree. I will open a new issue for that and close this one.

**Closed** 2015-10-01 21:29 UTC
Labels: invalid

**Comment by gilbertohasnofb** [comment] 2015-10-01 21:31
See #455.

**Comment by debdog** [comment] 2015-10-01 21:51
All right. Tanks!

**Comment by gilbertohasnofb** [comment] 2015-10-01 21:52
Thanks for the report!
