### ISSUE TITLE
floats (without wheels) on paved runway

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#194] opened 2015-05-19 17:32 UTC
on the floats, i turned them on while sitting on a paved runway and got a great tickle that the craft started moving about drifting in the wind... i hadn't even started the engine yet... when i did that, she was skating all over the place as if on ice... they shouldn't do that even on water with the engine at idle, should they? seems like there's a ""road friction"" number that may be just a tad too low when the pontoons are used...

yes, this is the same as i posted in the forums ;)

**Comment by gilbertohasnofb** [comment] 2015-05-19 18:41
A wild guess here: maybe that is related to the lack of parking brakes, have they been removed for the float version?

**Comment by wkitty42** [comment] 2015-05-19 20:29
that may be... but the brake lever is still in place and working under the ""steering wheel""...

**Comment by gilbertohasnofb** [comment] 2015-05-19 20:50
My guess was that the parking brake function was removed, and so the lever would not do anything.

**Comment by wkitty42** [comment] 2015-05-19 21:14
i dunno... i was able to set and unset it but it did no good :laughing:

**Comment by wlbragg** [comment] 2015-05-21 02:32
Attribute this to WIP. You guys are just too quick on the draw. I about laughed my ars off when I noticed the behavior. It's a simple fix. Go ahead and leave this issue until I fix it.

**Comment by wkitty42** [comment] 2015-05-21 16:49
here's a new thing as of at least commit [66b6fa6a]... i forgot that i had previously had the pontoons turned on... i loaded up with the new commit and went to heli view... there i switched to the default wheels but the craft body stayed in the air at the same height and angle it was with the floats... it was also drifting in the breeze as if the floats were still enabled... [repair] and switching between the other wheel types did not put the craft back on the ground or stop its drifting in the breeze... not sure i should add it as a new bug but this will work for reporting it :smile_cat:

**Comment by wlbragg** [comment] 2015-05-21 17:05
So when you started at an airport, you had left the float option checked when you properly shutdown the sim in the prior session?
Because of that, you basically lost control of switching gear types and were stuck on float (not visually though), only mechanically?
Did you ever sort it out and get it working correctly? How?

I think all this has to do with persistent data confusion, just a guess but that is where I am starting.

**Comment by wkitty42** [comment] 2015-05-21 17:21
yes, i had left floats selected when i shut down... after updating to the above mentioned commit, switching the floats off (at least while on land) does put the selected wheels back on the craft but it is still acting and sitting as if the floats are enabled... i forget the previous commit i had in place but it was working properly then... i /think/ commit [d30991b7] is the one where this started... i already had the merge of #197 and there's only been two commits since then...

**Comment by wlbragg** [comment] 2015-05-21 18:44
Dumb omission on my part, thanks for finding it, it should be fixed in latest commit.

**Comment by wlbragg** [comment] 2015-05-21 18:45
OK this should be able to be closed unless you think we need to adjust the ground friction even more. Test it and let me know.

**Comment by wkitty42** [comment] 2015-05-22 04:18
i'll test in a little bit and see that i can switch between wheels and pontoons properly... i'm not sure about the friction thing, though... unless we're saying that plain pontoons without wheels on pavement should not move at all in the breeze and may move when forced by full throttle??

**Comment by wkitty42** [comment] 2015-05-22 04:35
tested... i can properly switch between pontoons and wheels... that's one problem solved...

with pontoons, there is still some drift but full throttle doesn't make it go anywhere... the slow drift stays... switching to wheels rolls out like normal... i'm not sure we should see any drift with pontoons on pavement like a taxiway or runway... maybe on grass but only at full throttle? on water no drift other than maybe some with the breeze and possibly 50% throttle should influence directional control (rudder) and may add a little some to forward motion??

and on mention of forward motion, do these craft with pontoons have a reversible prop thrust capability for slowing and backing up on water or is that a whole different thing (fixed speed vs variable pitch)??

**Comment by wlbragg** [comment] 2015-05-23 03:06
Yeah, I noticed it still had a tiny bit of drift on land. I think we can correct that but I don't want to put too much effort in it until we see if it will be taken care of in the FDM.

**Comment by wkitty42** [comment] 2015-05-23 05:35
@wlbragg sounds fine by me... everyone should have a voice in this...

**Comment by wkitty42** [comment] 2015-05-23 15:09
i just updated to commit [d1240fd2] to play with the new pontoons... now when i'm sitting on a runway and switch to "floats", the craft starts bucking about like a bronco at a rodeo... high jumping, dancing and flipping about and just plain bucking... i can't tell if there's any drift still :laughing:

**Comment by wlbragg** [comment] 2015-05-23 20:16
Ooh, thanks, I just confirmed. It is only using pontoon not amphibious. I'll go fix that right now.

**Comment by wlbragg** [comment] 2015-05-23 20:41
OK, fixed it. The addition I had to make to mellow out the bounce of the amphibious broke the pontoon. All back to norm.

**Comment by wkitty42** [comment] 2015-05-23 21:56
yes, that fixed the bucking bronco :smile_cat: 

i think we're close with the pontoons... i might open an issue about the amphibious ones, though... they seem hard to steer (slow response) and apparently i bent one of the front ones up earlier and was unable to get it to straighten back out... i am not using the damage option (yet)... so so i make a new issue for that and anything else with the amphibious pontoons or??

**Comment by wlbragg** [comment] 2015-05-24 03:03
"they seem hard to steer (slow response)"
I think so too, thus my comment about some tuning.

"apparently i bent one of the front ones up earlier and was unable to get it to straighten back out..."
There is no damage modeled for the pontoons yet, I have no clue how or what you did that would have "bent" one?

**Comment by wkitty42** [comment] 2015-05-24 07:05
i think it happened when i landed in the grass beside the runway and tried to taxi back up onto the pavement which apparently was higher than i expected... i didn't discover the breakage until later when i landed on the water and beached her...

i saw the "damage" on the passenger side front wheel... instead of the wheel being down on the end of the pole/support, it was "bent up higher"... i could raise and lower the gear and this one would come down on the end of the pole/support and when fully extended it would then pop back up half way like it was bent... i can try to get pics if i see it again...

**Comment by wlbragg** [comment] 2015-05-25 00:03
I'm not happy at all with the amphibious gears bogie parameters. They need someone that knows this stuff really well to tune them.

What i do know is the compression on the gear is too great. Whether that is caused by weight or spring strength or a combination of both, I don't know.

**Comment by wkitty42** [comment] 2015-05-25 04:24
i understand... i haven't been able to reproduce the problem i reported but i have been trying...  i think it was just a(n un)lucky happenstance of speed and pressure that caused it to look and act as it did... even without any specific damage code involved...

**Comment by wlbragg** [comment] 2015-05-30 03:23
I think this can be closed also, This issue is being superseded by #214

**Comment by wkitty42** [comment] 2015-05-30 14:49
yeah, the drifting on pavement seems to be fixed now :)

**Closed** 2015-05-30 14:49 UTC
Labels: bug
