### ISSUE TITLE
Couple of bugs

### ISSUE THREAD

**Issue by legoboyvdlp** [Juanvvc/c172p-detailed#420] opened 2015-07-15 00:17 UTC
Hey guys just a couple of bugs....

One: Some instruments flicker or go black when under the ALS light. These are:
*Oil gauges
*Sound panel (with switches for mic/spkr)
*Transponder panel
*Directional Gyro
* Airspeed
*VOR 1 + 2

This is in the cold and dark state under the flashlight. Pictures: 
![fgfs-screen-008](https://cloud.githubusercontent.com/assets/10434911/8688021/4001c53c-2a60-11e5-9ee5-8d0b430a2a66.png)
![fgfs-screen-007](https://cloud.githubusercontent.com/assets/10434911/8688026/4c47a2ee-2a60-11e5-9080-b899f2b7cdec.png)

Also, there is a bug in the texture of the red stripe ... broken line. 
![fgfs-screen-005](https://cloud.githubusercontent.com/assets/10434911/8688035/67a7cc44-2a60-11e5-9a19-f70620cb2515.png)

Finally, the transponder digits are invisible at night. Flashlight on and off- same.

**Comment by wlbragg** [comment] 2015-07-15 04:21
I'm not able to reproduce the flashlight effect not
![flash](https://cloud.githubusercontent.com/assets/11069680/8690821/067d59e2-2a7f-11e5-851d-e3ab776e9f8b.jpg)
 working.

**Comment by wkitty42** [comment] 2015-07-15 04:48
i cannot reproduce this problem with the guages in any livery...

i do, however, have to agree with not being able to see the transponder digits at night with or without the flashllight... only in daylight do those numbers show up...

i'm also not sure about the red interior stripe, either... no clue where one is looking at for that...

**Comment by gilbertohasnofb** [comment] 2015-07-15 11:43
@legoboyvdlp Hi lego, thanks for the reports. First of all, next time you make a report here, please create a single issue for each bug you see, else we can't really organize our repository nor close the issue when one of them is solved. For this reason, I am closing this one and creating individual ones.

As for the bugs:
- I can't reproduce the problem with the gauges either
- I opened a new issue for the black radios under ALS flashlight here: #421
- As for the red lines, I agree they are not the prettiest thing on the planet. I will see if I can improve them here: #422

**Closed by gilbertohasnofb** 2015-07-15 11:43 UTC

**Comment by onox** [comment] 2015-07-15 11:50
@legoboyvdlp Are you running FG 3.5 and which video card brand do you have (Nvidia/AMD/Intel)?

**Comment by legoboyvdlp** [comment] 2015-07-15 18:29
Intel, FG 3.5
Detailed info here:
gl-vendor:Intel
gl-version:3.1.0 - Build 9.17.10.4101
gl-renderer:Intel(R) HD Graphics
gl-shading-language-version:1.40 - Intel Build 9.17.10.4101

If you move the flashlight around, especially to the edges, they go black. 
But that is with power off- that is battery on, cold and dark. Instrument lighting doesn't seem to make any difference. 
Also, it might be a night-time issue?

**Comment by legoboyvdlp** [comment] 2015-07-15 19:33
New instrument dark- clock
Daytime vs Night no diff.

**Comment by onox** [comment] 2015-07-15 20:25
I've got Intel too (with OS driver). Some of the instruments in the radio stack are indeed black, but the analog instruments around the yoke are okay.

**Comment by legoboyvdlp** [comment] 2015-07-16 16:23
Okay, so some of the analog instruments go black.
And some of the instruments disappear-- namely
*COM panel with speaker/headset switches
*Gauges for oil
*Autopilot

some others I cannot remember.
