### ISSUE TITLE
New FG release coming soon

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#803] opened 2016-08-06 21:26 UTC
@onox @wlbragg @Juanvvc @dany93 @dg-505 @wkitty42 

Torsten just wrote in the list:

> Hi all,
> 
> are we safe to pack the 2016.3.1 release in a bit less than two weeks or do we have any serious bugs to be fixed first?
> 
> Regards
> Torsten

So are we ready to ask for a merge? I would suggest we do that as soon as possible, as to avoid any problems like we had in the last release. Are there any serious issues or bugs we must address before the release?

**Comment by wkitty42** [comment] 2016-08-07 00:30
i'm not aware of anything other than this high altitude starting stuff you guys have been working on...

**Comment by gilbertohasnofb** [comment] 2016-08-07 09:52
:+1:

**Comment by gilbertohasnofb** [comment] 2016-08-07 18:25
@onox So should we prepare a release in our repo in the next days? After that we can then ask Stuart for merging it into FGDATA.

**Comment by onox** [comment] 2016-08-07 20:32
@gilbertohasnofb Are you able to add some shared objects from #725?

**Comment by gilbertohasnofb** [comment] 2016-08-07 20:35
@onox I can try having a look at it. Is there anything else we need to tackle for this release?

**Comment by onox** [comment] 2016-08-07 20:43
Not that I know.

It seems #725 is a duplicate of #717. You can close one of them as a duplicate (and remove the milestone).

**Comment by gilbertohasnofb** [comment] 2016-08-07 20:45
:+1:

**Comment by onox** [comment] 2016-08-07 20:49
How many days do we have left before they the core devs do their thing? I want to take a look at https://github.com/Juanvvc/c172p-detailed/issues/360#issuecomment-163194042 on tuesday or wednesday evening.

**Comment by gilbertohasnofb** [comment] 2016-08-07 20:52
Well, Torsten wrote this yesterday: 

> are we safe to pack the 2016.3.1 release in a bit less than two weeks

So there should be time. I will write Stuart right now and ask if we can have a merge by around the end of next week (12th of August), what do you say?

**Comment by onox** [comment] 2016-08-07 20:54
That's fine.

**Comment by gilbertohasnofb** [comment] 2016-08-07 20:55
So I will drop him an e-mail to let him know immediately about our intentions, this should avoid any problems like last time.

**Comment by gilbertohasnofb** [comment] 2016-08-07 20:59
Ok, so according to [this page](http://wiki.flightgear.org/Release_plan) the release is still being done on the 17th, so I think this proposal for the 12th should be fine. I will keep everyone posted here once I get an answer from Stuart.

**Comment by onox** [comment] 2016-08-07 21:25
#782 is another one that could be fixable.

**Comment by onox** [comment] 2016-08-08 21:36
@gilbertohasnofb Could you do #782 and perhaps #770?

**Comment by gilbertohasnofb** [comment] 2016-08-10 08:09
@onox I am not familiar with any of those. Maybe I could take a look at #770  but I know nothing about #782. Also, I am having some troubles with my connection since 2 days ago, so I am completely offline at home... O2 is coming to fix it today, so hopefully tonight I will be back online to do some work, but if I am not around you all know what happened, in which case someone should write Stuart by tomorrow.

**Comment by onox** [comment] 2016-08-11 11:52
@gilbertohasnofb Can you do #360? (Your solution) I would like to fix #118

**Comment by gilbertohasnofb** [comment] 2016-08-11 12:19
@onox sure, I will do it today. I think that solution will be simple enough to be easily implemented and then later easily removed when you or anyone else properly models the carburettor. As for #118, that's great you are fixing it! Remember to also take a look from the outside, as the glass looks bad both from the cockpit and from the exterior in this region where it connects to the wing.

**Comment by gilbertohasnofb** [comment] 2016-08-11 14:57
Stuart just wrote me:

> If you are able to have a release available by Friday 2000 UTC then I
> should be able to get it checked in Friday evening.  Any later and it
> may have to wait until Sunday, which is getting quite close to the
> release, but should still be OK.

I would strongly suggest we try to finish all the last minute work + review it by tonight, so that we have plenty of time for the release.

**Closed** 2016-08-12 18:02 UTC
Labels: help wanted, high priority, question

**Comment by onox** [comment] 2016-08-12 18:03
[Release](https://github.com/Juanvvc/c172p-detailed/releases) and branch [`release/2016.3`](https://github.com/Juanvvc/c172p-detailed/tree/release/2016.3)has been created.
