### ISSUE TITLE
Break wing inflight (+ gears on ground) due to excessive forces

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#134] opened 2015-04-30 18:43 UTC
This is one I really want to do. We have the modeled effect and the consequent FDM effect in place. I need the force calculations from the FDM?

**Comment by wlbragg** [comment] 2015-04-30 18:59
I just noticed #123 is this the same or tied to this new issue I created?

**Comment by dany93** [comment] 2015-04-30 22:27
Wing(s) can break because an excess of speed or by over-g's (excessive load factor).
Both due to an excessive force in reality. But in FG not the same properties.
/accelerations/n-z-cg-fpf_sec
/fdm/jsbsim/accelerations/Nz, pilot-gdamped
I do not know if you need all of them.
I should say that it is enough.

**Comment by onox** [comment] 2015-05-01 21:57
You could take a look at how the [f-14a](https://github.com/Zaretto/fg-aircraft/commit/1dfba02ca6d997607590df3eaff65088a0d9d629) implements this.

**Comment by wlbragg** [comment] 2015-05-02 09:03
I'll do that, thanks.

**Comment by wlbragg** [comment] 2015-05-07 05:18
Dany added some new FDM effects tied to these forces. We are currently testing them using a non-branched source. So far so good, they may need some fine tuning. It's a real sinking feeling to have a wing just quit working.

**Comment by wlbragg** [comment] 2015-05-07 06:06
Wow, Dany, does our existing FDM Juanvvc:master have the same spin effects when you loose the flight envelope as you have in dany93? The one wing "damage", INCREDIBLE. I tried to limp along back to the airport and screwed around till I got into a spin at low altitude, oops! This is really nice.
Again my question, does our existing Juanvvc:master FDM  have the same spin effects when you loose the flight envelope as you have in dany93 FDM?

I'm ready to merge Dany's FDM into master along with this new FDM damage model. It is incredible gang. Any comments anyone?

**Comment by dany93** [comment] 2015-05-07 14:13
>does our existing Juanvvc:master FDM have the same spin effects when you loose the flight envelope as you have in dany93 FDM?

Yes. it is the same for the "spin and stall" effects. I have not changed the general FDM other than for damages on left or /and right wings.
Easy to test: fly with the FDM from juanvvc (no damage effects), cut the throttle, hold the stick back, up to stalls. Worsen it with more or less rudder (see the slip ball).
I wonder if you do not mix two effects:
- one which have existed for a long time, the spin and stall effects, with can give a spin roll on stall, depending on your flight asymmetry (that is the original feature of this FDM, from the beginning you had it). That is when you are close to the edge or out of the flight envelope (high angles of attack),
- this very new damage effect, which is independent of the stall and spin (although a partly damaged wing can lead you to a stall and spin, as it seems to have happened to you).

Did I understand well and answer your question?
mmh... pardon, what does "incredible gang" means?....

**Comment by wlbragg** [comment] 2015-05-07 15:37
"incredible gang", means I really like your changes and also I really like the original spin modeling and I am telling our entire gang, working on this aircraft, that it is incredible work.:)
Even though that spin was original, that is the first time I ever experienced "getting out of the flight envelope", other than meeting the ground, can you believe that!

**Comment by wlbragg** [comment] 2015-05-09 07:03
Dany, I had to put your new FDM damage model on hold for a few days. I have to get the MP working first, I think it needs to take priority. I'm already sold on your changes though and want to replace any existing FDM damage modeling with it where appropriate (where the new and old overlap). I hope to get back to it by early next week.
The MP is a big bite to swallow.

**Comment by dany93** [comment] 2015-05-09 09:23
OK, thanks for the information, I had more or less understood that.

When you have made your mind and if you agree for the new controls, I can clean the physics.nas from the conditional FDMs and the previous useless properties.  Also if you like, update the "original" FDM.

I will let you for the damages on the ground.

**Comment by wlbragg** [comment] 2015-05-09 17:07
"I can clean the physics.nas from the conditional FDMs and the previous useless properties. Also if you like, update the "original" FDM."

Please do!

**Comment by dany93** [comment] 2015-05-09 18:27
I'll do it as soon as I can. This night if I can. If not, not sure for sunday... Sorry.

**Comment by dany93** [comment] 2015-05-10 22:07
Done.
http://www.mediafire.com/download/3tbxwr9upunmu4j/C172p-original-FDM-damage-20150510.7z
- Main file: "original" FDM with **wing-damage/left-wing, /right-wing** properties.
- I have also included the **physics.nas** file that I have used to test it. In this, I have deleted (commented) the conditions in FDMs to be as close as possible as it will be.
That's a working file, of course it needs cleaning. However, I think it can help.
It is more complete and better done than the previous one. If you start from one, please take this.

When you have made your modifications in physics.nas, we will have to delete the
```
		<wing>
            <broken-one type="double">0</broken-one>
            <broken-both type="double">0</broken-both>
        </wing>
```
in **c172p-detailed-set.xml**
(Not before, we would have nasal errors)

Still to observe if it works well for every features, I guess you have noticed that testing is not at all easy (almost stressful)...

V > 158 kt and flight asymmetry ==> one wing damaged
V > 180 kt and flight asymmetry ==> one wing broken
V > 200 kt ==> both wings broken

g > 4.4 and flight asymmetry ==> one wing damaged
g > 5.5 and flight asymmetry ==> one wing broken
g > 6.6 both wings broken

at which we might add: (??)
V > 180 kt and symmetric flight ==> both wings damaged

**Comment by wlbragg** [comment] 2015-05-13 04:44
"at which we might add: (??)
V > 180 kt and symmetric flight ==> both wings damaged (degraded lift)"

I like the idea...

**Comment by dany93** [comment] 2015-05-13 11:37
==> On the "To do" list (when it is be stabilized, I will pull from juanvvc, modify and do a Pull Request)

**Comment by dany93** [comment] 2015-05-17 10:52
>V > 180 kt and symmetric flight ==> both wings damaged (degraded lift)"

Done (currently only on my disk).

Moreover, prior to adding this into my branch and doing a Pull request, I' d like to have your opinion about some form changes in physics.nas.
- only one value for vne (no longer vne2), other values calculated,
- vne and max-g above these thresholds calculated by a factor (idea: max-max = 150% of specifs in terms of forces).

*(I have taken max-positive-g for "Normal" category, which lowers it: 3.8 instead of 4.4)*

Which gives, for the main changed lines:
```javascript
# Specifications Vne=158 KIAS,
# Normal category: max positive-g=3.8, max negative-g=1.52,
# Utility category: max positive-g=4.4, max negative-g=1.76,
# structure holds at least 150% max g's
props.globals.initNode("limits/max-positive-g", 3.8, "DOUBLE");
props.globals.initNode("limits/max-negative-g", -1.52, "DOUBLE");

#Over-speed	damages	 
	if (getprop("velocities/airspeed-kt") > (getprop("limits/vne") * 1.14)) # 180 KIAS
	{
        if (roll_moment > -4000 and roll_moment < 4000 and getprop("/fdm/jsbsim/wing-damage/left-wing") == 0 and getprop("/fdm/jsbsim/wing-damage/right-wing") == 0)
		{
			setprop("/fdm/jsbsim/wing-damage/left-wing", 0.3);
            setprop("/fdm/jsbsim/wing-damage/right-wing", 0.3);
			screen.log.write("Overspeed. Both wing DAMAGED ");
            gui.popupTip("Overspeed. Both wing DAMAGED", 5);
		}

	if (getprop("velocities/airspeed-kt") > (getprop("limits/vne") * 1.225)) # Vne x sqrt(1.5) ~ 200 KIAS

#Over-g damages
	if (g > (max_positive * 1.25))
	if (g > (max_positive * 1.5))
```
Also,
- You have seen my warning red messages on the screen for damage information. I've changed them for Popup messages (more visible).
- **I have tested a landing with both wings damaged: the engine stops when I am just above the ground**. It comes from your line nr 198:
```javascript
	if(getprop("position/altitude-agl-m") < 10 and (getprop("/fdm/jsbsim/crash") or getprop("/fdm/jsbsim/wing-damage/left-wing") or getprop("/fdm/jsbsim/wing-damage/right-wing")))
		killengine();
```
Another criteria should be chosen for "killing" the engine (nose wheel broken? very strong g's?).

Also if you prefer, the engine can be killed thanks to the (new) Float chamber, Systems/Fuel.xml, with
```
fdm/jsbsim/propulsion/tank[2]/priority = 0

```

Can you give me your opinion and, possibly, your agreement on these changes, for a Pull request?

**Comment by wlbragg** [comment] 2015-05-21 02:44
I good with all of it.
I'll rework the kill-engine condition for nose gear broke and wing "broken".
Plus I'll give it some more thought as to the original reason I kill it.

**Comment by dany93** [comment] 2015-05-21 10:10
Right, thanks wlbragg.
Also, see my Pull request comments https://github.com/Juanvvc/c172p-detailed/pull/197#issuecomment-104210991

**Comment by onox** [comment] 2015-05-30 09:46
This can be closed?

**Comment by dany93** [comment] 2015-05-30 12:55
Yes, IMO.

**Comment by onox** [comment] 2015-05-30 12:59
I noticed though it is very hard to break the gears, but not the wings. Should we open a new issue for this?

**Comment by dany93** [comment] 2015-05-30 13:55
Do you feel the wings are too easy to break?
Or do you rather mean this message https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-107039007 ?

**Comment by dany93** [comment] 2015-05-30 15:57
True.
In physics.nas, lines 227 and 231
```
        if(getprop(gears~"unit[1]/compression-ft") > 0.49 or getprop(gears~"unit[1]/broken"))
        if(getprop(gears~"unit[2]/compression-ft") > 0.49 or getprop(gears~"unit[2]/broken"))
```
A break threshold (compression-ft)  of 0.25 seems enough in practice (to be tested at full load, which I have done).

Not obvious from the calculation:
FDM: spring coefficient 5400 LBS/FT for each main gear;
0.25 ft compression corresponds to 5400 x 0.25 =1350 lbs per gear. If we assume both gears at touching: 2700 lbs. Which, with at full load = 2400 lbs, gives 2700 / 2400 = 1.125 g. Not much... should be easily attained...
But I guess the damping helps to avoid attaining the compression threshold in such a short time?

I let you think about it (no errors?) and do the tests.

**Comment by onox** [comment] 2015-05-30 19:48
> Decrease the damping in order to reach the compression threshold on a hard landing?

I think we should decrease the damping instead of the compression-ft. Do you agree?

**Comment by wkitty42** [comment] 2015-05-30 22:18
hey now! i resemble that comment :laughing:  but i'm actually trying to land decently... not bend and break things... but i'm getting better :wink:

**Comment by dany93** [comment] 2015-05-30 23:24
>I think we should decrease the damping instead of the compression-ft. Do you agree?

Yes, I think that would be be a good thing. I've not tested it, I had this idea just at the end of my tests.

**Comment by tigert** [comment] 2015-05-31 12:53
The nose gear compression to break it is a bit problematic, as I think the gear *can* sustain a compression to the end, if the force is straight, the nose gear arm is facing a bit forward.

What I am trying to test is the porpoise, where you land with excessive speed and often the aircraft starts leaping wiht increasing amplitude if you don't immediately arrest the movement by pulling back on the wheel and maybe add a bit of throttle to smoothen the next touchdown. If you do the very common mistake of pushing when the aircraft bounces (because you want to land! natural instinct) it will increase the size of the next bounce and eventually this leads to collapsing the nose gear.

This is the very common case when the gear breaks and it would be nice to be able to model that. I tried to test this by reducing the needed compression value a bit, and got it somewhat there, since I think it is a bit too strong initially, but then the problem is, that it also breaks if you put full throttle with parking brake on and push the stick forward. This compresses the gear too, and it collapses too. This is a bit unexpected, even though you usually don't hold brakes and push forward anyway. But maybe the compression ratio is a bit wrong parameter to check alone for gear collapsing. Side loads would be interesting to check too, like on crosswind landings with nasty bounces, it could collapse. But I don't know if those are available that easily from the FDM?

//T

**Comment by onox** [comment] 2015-06-01 17:01
Should we perhaps compute the force on the nose gear by computing pitching moment divided by distance from center to nose gear?

**Comment by dany93** [comment] 2015-06-01 17:53
What do you mean by pitching moment (which property)?
I have not found the forces on gears directly from jsbsim.
A rigorous way should be (if I understand well)
``` Force = (compression-ft) x (spring_coeff) + (compression-velocity-fps) x (damping_coeff)```
I have not tested it.

I'm struggling with this breaking threshold for the main gears.
I would prefer using properties directly available than swamping the (slow) nasal with these calculus for such a secondary behavior. But that's trial and error and compromises.... Maybe the above calculus will be the best solution....
If it is so simple, not having this done by JSBSim is weird.... JSBSim would do it much faster than nasal. Unless using switches, but we still add xml lines just for this....

**Comment by onox** [comment] 2015-06-01 18:54
I meant the moment around the y-axis. M = F * d.

**Comment by dany93** [comment] 2015-06-01 21:21
I understood, but where do you find this value of the moment in the properties?

**Comment by onox** [comment] 2015-06-01 22:02
Perhaps `/fdm/jsbsim/moments/m-gear-lbsft`?

**Comment by dany93** [comment] 2015-06-02 08:45
That was my first question here, with this possibility. https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-107653548.
I don't understand well what this moment is. From which axis? To counteract which moment when stopped on the ground?
If we have to do a calculus, I prefer
``` Force = (compression-ft) x (spring_coeff) + (compression-velocity-fps) x (damping_coeff)```
It is direct, easy to understand and rigorous. It can easily be applied separately on each gear.
I will try this, to see if I've understood well and if it works.

**Comment by onox** [comment] 2015-06-02 12:25
Ok, your equation seems better.

**Comment by dany93** [comment] 2015-06-02 14:34
I have a test file.
http://www.mediafire.com/download/wud4yvfdtbp80hq/C172-gear-damage-force-20150602.7z

Only for the principles, kind of feasibility, to get your opinion.

- In the **FDM**, only the damping for main gears is changed (400 instead of 1600 LBS/FT/SEC, lines 192 and 207). Does not seem very important, but I think 400 is better.
- **physics.nas** : TEST FILE For replacement. See lines 319 - 337.
Important: **MUST be the same coefficients as spring_coeff and damping_coeff in the FDM for each gear**.

Instead of breaking the gears and having to repair each time, I have made the forces on gears *printed* in the console above a threshold, which can be considered as the future breaking-threshold. By lowering the threshold, it can be used as a tool to measure these forces rather than doing trial and error.
The first values to be fiddled are the threshold forces.
For the nose, 1350 lbs is necessary to *not* break it on strong and long braking. It "breaks" on a strong nose contact.
For the main gears, I hesitate between 1500 and 2000 lbs. It must hold at full load and for crosswind landing.

More difficult to break at default loading, but if FG works well, the principle  seems realistic.

Some more complication in the nasal file because of the calculation lines, but after that the breaking criteria is obvious and the same as IRL.

Promising IMHO.

@tigert, if you can?
Also, I have found a *global* gear-Y-force in the FDM. It might be used to break the gear in crab landing or bad crosswind landing. I've not still tested.

**Comment by onox** [comment] 2015-06-02 14:44
@dany93 Just create a branch in your own repository:

1. `git checkout -b gear-changes`

2. Make the changes and commit them

3. `git push -u origin gear-changes`

**Comment by dany93** [comment] 2015-06-02 15:27
Done.
https://github.com/dany93/c172p-detailed/tree/gear-damage

**Comment by dany93** [comment] 2015-06-02 15:40
How can I recover the content I had in my branch "master" before these changes?
I've done ``git checkout master`` then ``git pull`` but, in my working directory, the files that I see on my disc inside my github folder are still with my last changes (physics.nas).

**Comment by onox** [comment] 2015-06-02 23:45
@dany93 Thanks. I'll test this tomorrow, it's night time currently.

**Comment by dany93** [comment] 2015-06-03 13:09
I have added a "print" in the console for the **side force on gears** (along Y-axis).
tigert wrote:
>Side loads would be interesting to check too, like on crosswind landings with nasty bounces

@tigert: what do you think we should set as a breaking threshold for this side force?
I'd say between 700 and 1000 lbs. It must hold crosswind landings at full load (not easy).

**Comment by dany93** [comment] 2015-06-03 13:55
@wlbragg
I have not understood well your links between the damages on wings and the 3D representation. As well as the damage names, the "var" in physics.nas

What I have seen:
- wing(s) slightly folded upwards with a high diedra. I'd say that's right for wings "damaged" (still able to fly); Typically partial damage inflight.
- wings folded downwards, touching the ground. Good for a very hard landing. Can be considered as "broken" on the ground.
- What I have not seen: one or both wings really broken inflight (at least half of them lacking). Possible with not too much work?

Will you take care of this when the breaking thresholds on the ground are set?
If I have to do it, I will need the properties or nasal variables in connection with the 3D results. 
And to agree, on the ground, which gear damage (or over g's on the ground) makes which 3D wing damage.

**Comment by onox** [comment] 2015-06-03 15:57
When you define a variable for the first time, you should add `var` so that it is a local variable. When you later assign a new value to it, you don't need to use `var` again.

**Comment by dany93** [comment] 2015-06-03 16:12
Yes, but this is a working file. I did not want to write everywhere.
In the "good" version, the variables will be defined as ```var = ``` at the top of the file, like those for wing damages. Inside the loop, only the name of the variable will be called.

**Comment by onox** [comment] 2015-06-03 16:15
Ok, I'll start testing your branch in an hour or so.

**Comment by onox** [comment] 2015-06-03 20:45
@dany93 I have tested your branch. The forces are nicely printed in the console. I think gear should break > 2000. Can you implement this in the current version? We can later tune the 3 numbers (the forces) if necessary.

**Comment by dany93** [comment] 2015-06-03 21:52
OK, the important was your agreement on the principle.
I update my master branch, introduce the gear breaking instead of the printing, and I do a pull request.
*(To morrow, now that's for me that it is late and I do not like make things in a hurry)*

**Comment by wkitty42** [comment] 2015-06-03 21:57
i was just playing with the current version and testing if the wings would fall off from overspeed... this is not with @dany93 stuff you have been talking about in recent posts... i got up to ~10000 and threw her into a dive... from chase or heli view, i saw "wing damage" reported but couldn't see anything... ok... then i saw the wings break outboard of the struts... i kept going looking to see if they'd come off but they didn't... it was a dance try to recover and she dived into the ground only to bounce some 2000 back up into the air :laughing: i did get into some spins but i don't know enough about how to recover from them... is quite freaky seeing everything spinning around from inside the cockpit and not knowing which way is which... i hope i never experience it in RL...

**Comment by onox** [comment] 2015-06-03 22:05
The wings can be heavily damaged, but cannot be separated. That would be cool though :smile:

**Comment by dany93** [comment] 2015-06-03 22:14
The 3D wing representation do not completely break them, it is a matter of animation. This is the subject of my question to wlbragg in this message https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-108431906.
I this situation, the "Repair" option is miraculous. After this and if you have been too long, Ctrl-u can help. No parachute is simulated...

**Comment by wkitty42** [comment] 2015-06-04 03:04
hahaha, i played the CTRL-U card numerous times, yes... as for slowing down, a lot of times after the breakage i was close to stall speed...

speaking of which, i haven't heard the stall horn in a while... i have to have my engine sounds turned down to hear the radios clearly... is the stall sound in the same ""voice"" as the engine sound? yeah, i now... probably another issue ;)

**Comment by wlbragg** [comment] 2015-06-04 06:26
dany, 
"What I have not seen: one or both wings really broken inflight "
I think we can do that, you want from the support strut to the tip "gone" broken off, yes?

**Comment by dany93** [comment] 2015-06-04 09:58
@wlbragg,
Yes, Nothing left beyond the strut. Tip "gone". Half of the wing.
I guess that's the easier from what you have already done, and it is enough to see what happened.

**Comment by wlbragg** [comment] 2015-06-04 16:09
We're on the same page!

"not what I "want""
I understand your explanation of not "wanting", as in a potential order or demand. I use the term "want" interchangeable with "mean", (probably my poor English skills even though it is my native language), I would never take coming anything from you that there was any intention other that simply trying to convey an idea. No worries!
It's a good idea and let's see if we can make it happen.

**Comment by wlbragg** [comment] 2015-06-05 05:21
Something like this?
![bwing1](https://cloud.githubusercontent.com/assets/11069680/7999895/c955da1a-0b18-11e5-9fd4-393143e5684c.jpg)
![bwing2](https://cloud.githubusercontent.com/assets/11069680/7999897/c957e418-0b18-11e5-8650-8c7faa35e0c7.jpg)
![bwing3](https://cloud.githubusercontent.com/assets/11069680/7999896/c957cae6-0b18-11e5-8cfd-6b2557366ce9.jpg)

**Comment by wlbragg** [comment] 2015-06-05 05:27
I guess it will take at least 4 new wings in the damage model.

I think we will need logic for the following

left broken, right no damage
left broken, right damaged
right broken, left no damage
right broken, left damaged

The pictures are of right broken, left damaged.

Do we also want both wings broken (as in both wings missing)?

**Comment by dany93** [comment] 2015-06-05 11:21
Very nice. Sure, people will be amused!

> Do we also want both wings broken (as in both wings missing)?

Yes.

I didn't realize it took one model per combination. I believed each part was independent.
We already have "left damaged", "right damaged", "both damaged".
With both wings broken it will be complete, this is the more important which is still lacking.
In case you would prefer limiting the number of combinations, if one wing is broken, that is not important to see the other damaged or not.

Which makes:
- both wings no damage (hopefully!)
- left no damage, right damaged
- left no damage, right broken
- left damaged, right no damaged
- left damaged, right damaged
- left broken, right no damage
- left broken, right broken

**Comment by onox** [comment] 2015-06-05 12:11
Why not make each side independent?

**Comment by dany93** [comment] 2015-06-05 13:40
Taking into account the problems with the floats and amphibious, I don't know if wlbragg has enough time to do important changes. But yes, it would be more flexible and easy to use.

**Comment by wkitty42** [comment] 2015-06-05 14:31
i like the pics... if there's enough time to get it in, go for it... but don't push it if there's too much other stuff to get done...

i kinda thought like @dany93 about the combinations... i know that some other (airliner) craft have wing flexure in their models... that requires that the wings be in multiple parts... if these wings are split into three parts, top center from strut to strut, left side wing and right side wing, then the bent up damage, bent down damage, folded down to the ground damage and completely broken off may be easier to do... maybe even two pieces for the left and right sides making 5 in total...

i don't know how complicated that would be for keeping them joined when undamaged and flying, though... this idea would probably be best for the next release after 3.6 but as i say above (and i keep saying) if it can be done in time and be working well, go for it... those of you doing the modeling and coding know what's involved better than others of us :wink: :+1:  i just wish i could really contribute more but that'll have to come later as time goes...

**Comment by wlbragg** [comment] 2015-06-05 17:33
"Why not make each side independent?"
I'd have to think about this one. Something tells me this would be a lot of work?
Maybe not, but just the modeling alone would take me quite a while. Issues would be, unless we used (cut up) existing wings all the lights pos might change slightly (that is considerable work, verifying it all in MP, potential major overhaul to the logic involved. It just seems like it would be really major, but it might not be that bad if we think it through.
I would wait till next cycle to entertain it.

I'll immediately add both broken.

Do you see left or right broken without damage to the other side?

**Comment by dany93** [comment] 2015-06-05 18:07
> Do you see left or right broken without damage to the other side?

Yes, if possible (sorry...).
This is the case when the aircraft starts spinning and falling down. The remaining wing can be left (seen) as normal, no matter it is partially damaged or not.

**Comment by onox** [comment] 2015-06-05 18:19
@wlbragg Can you get this done before the feature freeze deadline? Or should we postpone it for 3.8?

**Comment by wlbragg** [comment] 2015-06-05 18:32
I think so, I already have the both broken (I think). How many days left?

**Comment by onox** [comment] 2015-06-05 18:43
17th of June is the deadline for new features.

**Comment by wlbragg** [comment] 2015-06-05 19:01
Yes, I can get the broken done.

**Comment by wkitty42** [comment] 2015-06-05 19:10
i was going to say 7 days left if you wanted to target the 12th as @gilbertohasnofb is doing with his scenery stuff... that'll give the core guys some time to check it over before the *feature* freeze... bug fixes can still be handled and submitted after the freeze, though... at least that's my understanding...

**Comment by onox** [comment] 2015-06-05 19:37
But feature freeze of fgdata is on the 17th. All we have to do is promise not to sneak in any new features after that data.

**Comment by wkitty42** [comment] 2015-06-06 01:03
true but better to have a bit of a buffer than none and overrun :wink:

**Comment by wlbragg** [comment] 2015-06-06 08:48
I made major progress on this tonight. I think I have all five wing models finished and the "both wings broke" coded in and ready to go.

All that is left is to code the following four.

left damaged, right broken
left undamaged, right broken
right damaged, left broken
right undamaged, left broken

Should have it pushed for a pull requests by late tomorrow night.

![bothbroke](https://cloud.githubusercontent.com/assets/11069680/8019008/cd624b34-0bfe-11e5-988b-f39c1cfa280c.jpg)

**Comment by dany93** [comment] 2015-06-06 09:05
>left damaged, right broken
right damaged, left broken

Are these really necessary? When one wing is broken, I think that merely *seeing* the other one *not broken* is enough. Damaged or intact is not important, I would use "intact" model in both cases.
You save two wing models.
See my message https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-109261002

**Comment by wlbragg** [comment] 2015-06-06 15:13
Necessary no, but their done and I figured that you would normally damage and then break a wing (in that order). So I thought it best that we have it both ways. I think for the most part the logic is already in place so if you damage a wing or both and keep applying force then they will eventually break. Or you could have the instance where you go right from good to broke, I guess.

**Comment by dany93** [comment] 2015-06-06 15:34
Yes, we can have instances where one is only damaged and the other broken. If you have already done them, it is not too much and not an inconvenience, only best.
I said this only to save you some time.

**Comment by wlbragg** [comment] 2015-06-06 17:39
This is going to need some tuning I think. It appears the wing breaking is fairly easy and I think need to be harder.

Here are the parameters we will have to work with

Everything as it is now and what more we will have to work with.

You originally created two wing damage properties wing-damage/left-wing and right-wing. 

You used basically two damage amounts to control damaged or broken in FDM,
where damaged is < 1 and broken = 1 
wing-damage = 1 triggers wing broken (complete loss of control) and broken wing animation 
wing-damage < 1 is the amount applied to loss of control and will trigger damage animation

I used originally used
contacts[4]/broken
contacts[5]/broken
and crash (this was for collapsed wings)
to control animation

I added a new property to help with animation and nasal control, it is 
wing-both/broken

Each one of these has an alias for animation control local and over MP

So we now have
6 alias we will use to control animations
<crash> = /fdm/jsbsim/crash
<wing_left_broken> = /fdm/jsbsim/contact/unit[4]/broken
<wing_right_broken> = /fdm/jsbsim/contact/unit[5]/broken
<wing_both_broken> = /fdm/jsbsim/wing-both/broken
<wing_left_damaged> = /fdm/jsbsim/wing-damage/left-wing
<wing_right_damaged> = /fdm/jsbsim/wing-damage/right-wing
		
and we have
6 properties we will use to control nasal and FDM
/fdm/jsbsim/crash
/fdm/jsbsim/contact/unit[4]/broken
/fdm/jsbsim/contact/unit[5]/broken
/fdm/jsbsim/wing-both/broken
/fdm/jsbsim/wing-damage/left-wing
/fdm/jsbsim/wing-damage/right-wing

We may need a little bit of adjustment in how we use them on both FDM/nasal and animation now that we have this complete set of conditions.

Right now I'm finishing up getting all the light animation logic, wing animation logic and wing nasal logic to a point where it is at least correct (but maybe not adjusted perfectly), at which point I'll push to a branch, then I really could use some help fine tuning the damage logic in physics.nas to get it exactly how we want it.

**Comment by dany93** [comment] 2015-06-06 22:14
I do not see
wing_both_damaged
wing_both/damaged
?
>It appears the wing breaking is fairly easy and I think need to be harder.

If a wing has touched the ground, even not violently, the aircraft no longer takes off.

**Comment by wlbragg** [comment] 2015-06-07 03:41
We don't have a wings-both-damaged, we use "wing-left-damaged and wing-right-damaged" for both.

The animation logic is taking a bit longer than I anticipated, I am doing a bit of refactoring in an effort to get rid of a bunch of extra model part (like I did a while back with gear and propeller). Hopefully I'll push a pull request tonight (in the next couple hours).

**Comment by wkitty42** [comment] 2015-06-07 05:24
@wlbragg yo are doing good, man! don't rush things... it only leads to misteaks  :wink:

**Comment by wlbragg** [comment] 2015-06-08 19:41
We can close this now if there are no other issues to discuss. iif

**Comment by onox** [comment] 2015-06-09 02:57
I have issues with it unfortunately :cry: See PR #262

**Comment by onox** [comment] 2015-06-10 14:04
@wlbragg There's one small issue with the landing light if the left wing has been torn off; it's still visible:

![fgfs-screen-025](https://cloud.githubusercontent.com/assets/3361585/8084205/1c763aa8-0f8a-11e5-8ff5-0f97dd88c197.png)

**Comment by onox** [comment] 2015-06-10 14:14
I just tried to pull the yoke back hard and the wings broke away in air:

![fgfs-screen-026](https://cloud.githubusercontent.com/assets/3361585/8084437/50da28c6-0f8b-11e5-810f-f4ab3dfe1eaa.png)

IMO that should not have happened. The wing should be damaged (bended a little), but not completely torn off :confused:

**Comment by dany93** [comment] 2015-06-10 14:48
https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-100706694

V > 180 kt and symmetric flight ==> both wings damaged (degraded lift)

g > 4.4 and flight asymmetry ==> one wing damaged (can still fly, degraded)
g > 5.5 and flight asymmetry ==> one wing broken
g > 6.6 both wings broken

We can do what we want, but who can say IRL? With these features, we are more in the estimation for the game than in realism... I am not able to affirm that a very short but brutal over-g (here > 1.5 x specs) do not break one or both wings.

**Comment by wlbragg** [comment] 2015-06-11 03:13
"You can edit Systems/als-lights.xml for this."
Do you know if this will take aliases?
You did not set up an alias for ALS landing light in MP?

**Comment by wlbragg** [comment] 2015-06-11 03:14
" landing light if the left wing has been torn off; it's still visible:"
I have this fixed already, will PR shortly, after I fix ALS landing and taxi light for the same issue.

**Comment by onox** [comment] 2015-06-11 10:25
@Juanvvc @gilbertohasnofb What do you guys think of the over-g?

**Comment by wlbragg** [comment] 2015-06-11 17:00
It's not helpful, but I was going to tell you to quite abusing you plane! :)

I think that is the same thing I was a little concerned about.
Strictly going by feel (no real quantifiable data), it seems that at the point of total wing destruction (broken wings) it should only be damaged wings, and that the "broken wings" bar should be somewhat higher.

**Comment by onox** [comment] 2015-06-11 17:20
Maybe we can first try to just increase the g limits?

**Comment by wlbragg** [comment] 2015-06-11 17:21
Agreed, we can fine tune it in the next cycle if we choose.

**Comment by onox** [comment] 2015-06-13 05:31
@wlbragg Shall I close this issue? We can create a separate issue with the 3.6 release milestone for tuning the g limits.

**Comment by wlbragg** [comment] 2015-06-13 08:41
OK

**Closed** 2015-06-13 08:52 UTC
Labels: 3D model, animations (XML), enhancement, FDM, help wanted, question
